### ISSUE TITLE
 Null pointer when click on Print after placing the order

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1070]
Steps
place an order with the payment mode as counter cash
click on receive payment 
Click on print

`HTTP Status 500 – Internal Server Error
Type Exception Report

Message Unhandled exception in exception handler.

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

net.sourceforge.stripes.exception.StripesServletException: Unhandled exception in exception handler.
	net.sourceforge.stripes.exception.DefaultExceptionHandler.handle(DefaultExceptionHandler.java:160)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:250)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
Root Cause

java.lang.NullPointerException
Note The full stack trace of the root cause is available in the server logs.

Apache Tomcat/8.5.20`

**Logs**
`-8181-exec-32] (14 Jan 2020 11:15:23) (POSServiceImpl.java:793) - Ajency.in :: fefo enabled false
[ INFO] [] [http-nio-8181-exec-32] (14 Jan 2020 11:15:23) (POSServiceImpl.java:808) - Fefo discount not applicable for variant HealthKart Hair, Skin & Nails,  90 capsules  Unflavoured 
[ INFO] [] [http-nio-8181-exec-32] (14 Jan 2020 11:15:23) (ProductVariantServiceImpl.java:471) - Ajency.in :: NPL FLASH Discount Config true
[ INFO] [] [http-nio-8181-exec-32] (14 Jan 2020 11:15:23) (ProductVariantServiceImpl.java:473) - Ajency.in :: flash discount enabled for store
[ INFO] [] [http-nio-8181-exec-32] (14 Jan 2020 11:15:23) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/sale/flashDeal/-1/HNUT8979-01?z.ts==1578980723092&st=1  RC: 200
[ INFO] [] [http-nio-8181-exec-32] (14 Jan 2020 11:15:23) (HkHttpClient.java:109) -  http T:0 ms 
[ INFO] [] [http-nio-8181-exec-32] (14 Jan 2020 11:15:23) (HkHttpClient.java:129) -  parsing T:3 ms 
[ INFO] [] [http-nio-8181-exec-32] (14 Jan 2020 11:15:23) (POSHelper.java:103) - Ajency.in:: Adding vendor to poslineitems >= 2
[ INFO] [] [http-nio-8181-exec-32] (14 Jan 2020 11:15:23) (POSHelper.java:190) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-32] (14 Jan 2020 11:15:23) (POSAction.java:3793) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-32] (14 Jan 2020 11:15:23) (POSAction.java:3794) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-32] (14 Jan 2020 11:15:23) (HkHttpClient.java:267) - Ajency.in :: parsing json response
[ INFO] [] [http-nio-8181-exec-32] (14 Jan 2020 11:15:23) (ThirdPartyPaymentServiceImpl.java:336) - Ajency.in :: has pending transactions false
[ INFO] [] [pool-24-thread-1] (14 Jan 2020 11:15:45) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (14 Jan 2020 11:15:45) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false
[ INFO] [] [http-nio-8181-exec-42] (14 Jan 2020 11:15:50) (GSTInvoiceAction.java:133) - Ajency.in :: re generating pdf for shipping order id 5925204
[ INFO] [] [http-nio-8181-exec-42] (14 Jan 2020 11:15:50) (GSTInvoiceDTO.java:110) - Ajency.in:: total line items for invoice > 1
[ INFO] [] [http-nio-8181-exec-42] (14 Jan 2020 11:15:50) (GSTInvoiceDTO.java:114) - Ajency.in:: Invoice eligible for clubbing
[ INFO] [] [http-nio-8181-exec-42] (14 Jan 2020 11:15:50) (GSTInvoiceDTO.java:159) - Ajency.in:: Product line item for invoice: HealthKart Lung Detox,  90 capsules 
[ INFO] [] [http-nio-8181-exec-42] (14 Jan 2020 11:15:50) (GSTInvoiceDTO.java:259) - Ajency.in:: LI packmap is empty
[ INFO] [] [http-nio-8181-exec-42] (14 Jan 2020 11:15:50) (GSTInvoiceDTO.java:307) - Ajency.in:: Total invoice items > 1
[ INFO] [] [http-nio-8181-exec-42] (14 Jan 2020 11:15:50) (GSTInvoiceServiceImpl.java:399) - Ajency.in :: pdf file path : /usr/local/projects/tomcat_aqua/webapps/ROOT/gstInvoicePDF/SO_5925204_1578980750985.pdf
[ERROR] [] [http-nio-8181-exec-42] (14 Jan 2020 11:15:50) (SOGSTInvoiceGenerator.java:116) - /usr/local/projects/tomcat_aqua/webapps/ROOT/images/truebasics-invoice-header.jpeg (No such file or directory)
java.io.FileNotFoundException: /usr/local/projects/tomcat_aqua/webapps/ROOT/images/truebasics-invoice-header.jpeg (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)
	at com.itextpdf.text.Image.getInstance(Image.java:260)
	at com.itextpdf.text.Image.getInstance(Image.java:241)
	at com.itextpdf.text.Image.getInstance(Image.java:364)
	at com.hk.admin.util.SOGSTInvoiceGenerator.createImageHeader(SOGSTInvoiceGenerator.java:135)
	at com.hk.admin.util.SOGSTInvoiceGenerator.generateInvoicePDF(SOGSTInvoiceGenerator.java:93)
	at com.hk.admin.impl.service.accounting.GSTInvoiceServiceImpl.generateSOGSTPdf(GSTInvoiceServiceImpl.java:403)
	at com.hk.admin.impl.service.accounting.GSTInvoiceServiceImpl.generateAndUploadInvoice(GSTInvoiceServiceImpl.java:430)
	at com.hk.web.action.core.accounting.GSTInvoiceAction.downloadInvoiceAsPdf(GSTInvoiceAction.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] [] [http-nio-8181-exec-42] (14 Jan 2020 11:15:50) (GSTInvoiceServiceImpl.java:450) - Ajency.in :: Exception occured 
ExceptionConverter: 
java.io.IOException: The document has no pages.
	at com.itextpdf.text.pdf.PdfPages.writePageTree(PdfPages.java:112)
	at com.itextpdf.text.pdf.PdfWriter.close(PdfWriter.java:1256)
	at com.itextpdf.text.pdf.PdfDocument.close(PdfDocument.java:901)
	at com.itextpdf.text.Document.close(Document.java:415)
	at com.hk.admin.util.SOGSTInvoiceGenerator.generateInvoicePDF(SOGSTInvoiceGenerator.java:117)
	at com.hk.admin.impl.service.accounting.GSTInvoiceServiceImpl.generateSOGSTPdf(GSTInvoiceServiceImpl.java:403)
	at com.hk.admin.impl.service.accounting.GSTInvoiceServiceImpl.generateAndUploadInvoice(GSTInvoiceServiceImpl.java:430)
	at com.hk.web.action.core.accounting.GSTInvoiceAction.downloadInvoiceAsPdf(GSTInvoiceAction.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[ INFO] [] [http-nio-8181-exec-42] (14 Jan 2020 11:15:50) (GSTInvoiceAction.java:136) - Ajency.in :: pdf link : null
[ WARN] [] [http-nio-8181-exec-42] (14 Jan 2020 11:15:50) (Log.java:94) - Unhandled exception caught by the Stripes default exception handler.
java.lang.NullPointerException
[ERROR] [] [http-nio-8181-exec-42] (14 Jan 2020 11:15:50) (Log.java:82) - Unhandled exception in exception handler.
java.lang.NullPointerException
[ INFO] [] [pool-24-thread-1] (14 Jan 2020 11:20:00) (UploadUsersScheduler.java:52) - Ajency.in :: Schedule Upload Users ::  Upload Users Campaign Cron Executed:1578981000000
[ INFO] [] [pool-24-thread-1] (14 Jan 2020 11:20:00) (UploadUsersScheduler.java:68) - Ajency.in :: Schedule Upload Users :: uploadUsersEnableCron : true uploadUsersThreshold : 1000 uploadUsersEmailAddress : analytics@brightlifecare.com uploadUsersCronStartTime : 22:00:00 uploadUsersPerDayLimit : 800
`

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/72319209-95076080-36c4-11ea-9793-2dc92e6b769e.png)

**Comment by shivam-kurtarkar** [comment]
wrong file path environment property issue ->  /usr/local/projects/tomcat_aqua/webapps  should be tomcat_aqua_new
