### ISSUE TITLE
cannot initiate transaction, "Failed to Initiate Transaction, please try again. null" message is displayed on click of initiate payment

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1100]
Actual result
cannot initiate transaction, "Failed to Initiate Transaction, please try again. null" message is displayed on click of initiate payment

Expected result
User should be able to initiate the transaction.

`[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (POSAction.java:2795) - Ajency.in :: payment mode : 100: Credit/Debit Card
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (POSAction.java:2799) - Ajency.in :: payment mode upi || card || split
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (POSAction.java:2808) - Ajency.in :: trying to fetch customer order by id :1235785
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (POSAction.java:2834) - Ajency.in :: order count:0
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:368) - Ajency.in :: DEV :: customer order transaction id: 12 status: 5
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:381) - Ajency.in :: has pending transactions false for 1235785
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (POSServiceImpl.java:753) - Ajency.in :: updating customer order :1235785
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (POSServiceImpl.java:764) - Ajency.in :: applied coupon code during creating customer order: null
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (POSAction.java:2848) - Ajency.in :: final payable  rounded amount :1529.0
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:85) - Ajency.in :: customer order id :1235785 transaction id 1235785-1579154621595
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:457) - Ajency.in :: transaction number :1235785-1579154621595 amount:152900
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:468) - Ajency.in :: resultset: true
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:471) - Ajency.in :: forcePinelabsInitApiCall true active :false
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:417) - Ajency.in :: fetching pinelabs config for store 4034
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:505) - Ajency.in :: pinelabs params {"SecurityToken":"661c9a5f-5d7a-4d76-a950-68beb8225cfd","TransactionNumber":"1235785-1579154621595","AllowedPaymentMode":"1","UserID":15563757,"Amount":152900,"SequenceNumber":1,"MerchantStorePosCode":"9808798797","IMEI":"60987097","MerchantID":2300}
[ERROR] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (URIBuilder.java:73) - failed to parse 
java.lang.NullPointerException
	at com.hk.util.http.URIBuilder.fromURI(URIBuilder.java:58)
	at com.hk.admin.impl.service.accounting.ThirdPartyPaymentServiceImpl.initiatePinelabsTransaction(ThirdPartyPaymentServiceImpl.java:508)
	at com.hk.admin.impl.service.accounting.ThirdPartyPaymentServiceImpl.initiateTransaction(ThirdPartyPaymentServiceImpl.java:86)
	at com.hk.web.action.admin.pos.POSAction.initiatePayment(POSAction.java:2849)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:509) - Ajency.in :: making url call to  https://www.plutuscloudserviceuat.in:8201/API/CloudBasedIntegration/V1/UploadBilledTransaction
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (HkHttpClient.java:267) - Ajency.in :: parsing json response
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:390) - Ajency.in :: openTransactionErrorMessage
[ERROR] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:406) - Ajency.in:: Failed to create open transaction message
java.lang.NullPointerException
	at com.hk.admin.impl.service.accounting.ThirdPartyPaymentServiceImpl.openTransactionErrorMessage(ThirdPartyPaymentServiceImpl.java:395)
	at com.hk.admin.impl.service.accounting.ThirdPartyPaymentServiceImpl.initiatePinelabsTransaction(ThirdPartyPaymentServiceImpl.java:520)
	at com.hk.admin.impl.service.accounting.ThirdPartyPaymentServiceImpl.initiateTransaction(ThirdPartyPaymentServiceImpl.java:86)
	at com.hk.web.action.admin.pos.POSAction.initiatePayment(POSAction.java:2849)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:521) - Ajency.in :: Pinelabs api call :1 : INVALID IMEI
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:535) - Ajency.in :: pinelabs response {"responseCode":1,"responseMessage":"INVALID IMEI","plutusTransactionReferenceID":-1}
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:543) - Ajency.in :: pinelabs api call for transaction 1235785-1579154621595 PlutusTransactionReferenceID:null
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:545) - Ajency.in :: messages: null
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:103) - Ajency.in :: saved customerOrderTransaction 13 transactionId :1235785-1579154621595
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:106) - Ajency.in :: messages: null
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:368) - Ajency.in :: DEV :: customer order transaction id: 12 status: 5
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:368) - Ajency.in :: DEV :: customer order transaction id: 13 status: 5
[ INFO] [] [http-nio-8181-exec-10] (16 Jan 2020 11:33:41) (ThirdPartyPaymentServiceImpl.java:381) - Ajency.in :: has pending transactions false for 1235785

`

**Comment by larissa-c-d** [comment]
Failed to Initiate Transaction, please try again.
null message is displayed on click of initiate button

`[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (POSAction.java:2797) - Ajency.in :: payment mode : 600: UPI via EDC Machine
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (POSAction.java:2801) - Ajency.in :: payment mode upi || card || split
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (POSAction.java:2810) - Ajency.in :: trying to fetch customer order by id :1236047
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (POSAction.java:2834) - Ajency.in :: order count:0
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (ThirdPartyPaymentServiceImpl.java:387) - Ajency.in :: DEV :: customer order transaction id: 625 status: 5
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (ThirdPartyPaymentServiceImpl.java:400) - Ajency.in :: has pending transactions false for 1236047
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (POSServiceImpl.java:753) - Ajency.in :: updating customer order :1236047
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (POSServiceImpl.java:764) - Ajency.in :: applied coupon code during creating customer order: null
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (POSAction.java:2848) - Ajency.in :: final payable  rounded amount :6159.0
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (ThirdPartyPaymentServiceImpl.java:88) - Ajency.in :: customer order id :1236047 transaction id 1236047-1579180194283
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (ThirdPartyPaymentServiceImpl.java:478) - Ajency.in :: transaction number :1236047-1579180194283 amount:615900
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (ThirdPartyPaymentServiceImpl.java:489) - Ajency.in :: resultset: true
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (ThirdPartyPaymentServiceImpl.java:492) - Ajency.in :: forcePinelabsInitApiCall true active :false
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (ThirdPartyPaymentServiceImpl.java:438) - Ajency.in :: fetching pinelabs config for store 4034
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (ThirdPartyPaymentServiceImpl.java:526) - Ajency.in :: pinelabs params {"SecurityToken":"661c9a5f-5d7a-4d76-a950-68beb8225cfd","TransactionNumber":"1236047-1579180194283","AllowedPaymentMode":"10","UserID":15563757,"Amount":615900,"SequenceNumber":1,"MerchantStorePosCode":"04190588","IMEI":"IM239018","MerchantID":2300}
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (ThirdPartyPaymentServiceImpl.java:537) - Ajency.in :: resultset: https://www.plutuscloudserviceuat.in:8201/API/CloudBasedIntegration/V1/
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (ThirdPartyPaymentServiceImpl.java:540) - Ajency.in :: pinelabsurl https://www.plutuscloudserviceuat.in:8201/API/CloudBasedIntegration/V1/ active :false
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:39:54) (ThirdPartyPaymentServiceImpl.java:553) - Ajency.in :: making url call to  https://www.plutuscloudserviceuat.in:8201/API/CloudBasedIntegration/V1/UploadBilledTransaction
[ INFO] [] [pool-24-thread-1] (16 Jan 2020 18:40:00) (UploadUsersScheduler.java:52) - Ajency.in :: Schedule Upload Users ::  Upload Users Campaign Cron Executed:1579180200003
[ INFO] [] [pool-24-thread-1] (16 Jan 2020 18:40:00) (UploadUsersScheduler.java:68) - Ajency.in :: Schedule Upload Users :: uploadUsersEnableCron : true uploadUsersThreshold : 1000 uploadUsersEmailAddress : analytics@brightlifecare.com uploadUsersCronStartTime : 22:00:00 uploadUsersPerDayLimit : 800
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:40:09) (ThirdPartyPaymentServiceImpl.java:409) - Ajency.in :: openTransactionErrorMessage
[ERROR] [] [http-nio-8181-exec-120] (16 Jan 2020 18:40:09) (ThirdPartyPaymentServiceImpl.java:565) - Ajency.in :: Pinelabs api call :1 : DB OPERATION FAILED
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:40:09) (ThirdPartyPaymentServiceImpl.java:579) - Ajency.in :: pinelabs response {"responseCode":1,"responseMessage":"DB OPERATION FAILED","plutusTransactionReferenceID":-1}
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:40:09) (ThirdPartyPaymentServiceImpl.java:587) - Ajency.in :: pinelabs api call for transaction 1236047-1579180194283 PlutusTransactionReferenceID:null
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:40:09) (ThirdPartyPaymentServiceImpl.java:589) - Ajency.in :: messages: null
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:40:09) (ThirdPartyPaymentServiceImpl.java:106) - Ajency.in :: saved customerOrderTransaction 626 transactionId :1236047-1579180194283
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:40:09) (ThirdPartyPaymentServiceImpl.java:109) - Ajency.in :: messages: null
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:40:09) (ThirdPartyPaymentServiceImpl.java:387) - Ajency.in :: DEV :: customer order transaction id: 625 status: 5
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:40:09) (ThirdPartyPaymentServiceImpl.java:387) - Ajency.in :: DEV :: customer order transaction id: 626 status: 5
[ INFO] [] [http-nio-8181-exec-120] (16 Jan 2020 18:40:09) (ThirdPartyPaymentServiceImpl.java:400) - Ajency.in :: has pending transactions false for 1236047

`
