### ISSUE TITLE
Duplicate entries in the retail_store_pinelabs_config table.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1122]
`

[ INFO] [] [http-nio-8181-exec-7] (17 Jan 2020 11:30:08) (LoginAction.java:72) - Ajency.in :: DEV >>>>>>>>>>>>>>>>>>> :: trying to login for email: jagriti.dhawan@brightlifecare.com
[ INFO] [] [http-nio-8181-exec-7] (17 Jan 2020 11:30:08) (UserServiceImpl.java:58) - Ajency.in :: DEV >>>>>>>>>>>>>> :: healthkart login exception thrown for email: jagriti.dhawan@brightlifecare.com
[ INFO] [] [http-nio-8181-exec-7] (17 Jan 2020 11:30:08) (LoginAction.java:75) - Ajency.in :: DEV :: login exception:
com.hk.exception.HealthkartLoginException: org.apache.shiro.authc.AuthenticationException: Authentication failed for token submission [org.apache.shiro.authc.UsernamePasswordToken - jagriti.dhawan@brightlifecare.com, rememberMe=true].  Possible unexpected error? (Typical or expected login exceptions should extend from AuthenticationException).
       at com.hk.impl.service.core.UserServiceImpl.login(UserServiceImpl.java:60)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
       at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
       at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
       at com.hk.aop.BusinessMethodTimeProfiler.profile(BusinessMethodTimeProfiler.java:28)
       at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)`

**Comment by sharangsamonkar** [comment]
Duplicate entries will not get created.
