### ISSUE TITLE
"Failed to Initiate Transaction, please try again." is displayed on click of initiate transaction.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1142]
Actual result
"Failed to Initiate Transaction, please try again." is displayed on click of initiate transaction.

**Comment by sharangsamonkar** [comment]
Need to check if this comes up again.

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/72778272-76faac80-3c3e-11ea-90f7-b46ae02b7327.png)

**Comment by larissa-c-d** [comment]
`[ INFO] [] [http-nio-8181-exec-1] (21 Jan 2020 11:05:26) (HkHttpClient.java:109) -  http T:0 ms 
[ INFO] [] [http-nio-8181-exec-1] (21 Jan 2020 11:05:26) (HkHttpClient.java:129) -  parsing T:2 ms 
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (POSHelper.java:190) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (POSAction.java:3911) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (POSAction.java:3912) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (POSServiceImpl.java:798) - Ajency.in :: fefo enabled true
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (POSServiceImpl.java:978) - Ajency.in :: existing product variant found
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (POSServiceImpl.java:979) - Ajency.in :: flash discount applied 0.0
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (POSServiceImpl.java:813) - Fefo discount not applicable for variant HealthKart 100% Pure Whey Protein,  2.2 lb  Unflavoured 
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (ProductVariantServiceImpl.java:471) - Ajency.in :: NPL FLASH Discount Config true
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (ProductVariantServiceImpl.java:473) - Ajency.in :: flash discount enabled for store
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/sale/flashDeal/0/HNUT10976-01?z.ts==1579584928045&st=1  RC: 200
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (HkHttpClient.java:109) -  http T:0 ms 
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (HkHttpClient.java:129) -  parsing T:2 ms 
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (POSHelper.java:190) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (HkHttpClient.java:290) - Ajency.in :: IO Exception: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: org.apache.commons.httpclient.AutoCloseInputStream@45fbf556; line: 1, column: 2]
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (HkHttpClient.java:294) - Ajency.in :: IO Exception Stacktrace: org.codehaus.jackson.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: org.apache.commons.httpclient.AutoCloseInputStream@45fbf556; line: 1, column: 2]
	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._throwInvalidSpace(JsonParserMinimalBase.java:467)
	at org.codehaus.jackson.impl.Utf8StreamParser._skipWSOrEnd(Utf8StreamParser.java:2322)
	at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:444)
	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2770)
	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2691)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1286)
	at org.codehaus.jackson.JsonParser.readValueAs(JsonParser.java:1337)
	at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:268)
	at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:238)
	at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:205)
	at com.hk.api.edge.integration.impl.service.variant.HkVariantServiceImpl.getOffersForCart(HkVariantServiceImpl.java:78)
	at com.hk.web.action.admin.pos.POSAction.getOffersForCart(POSAction.java:4309)
	at com.hk.web.action.admin.pos.POSAction.getCartOffers(POSAction.java:2555)
	at com.hk.web.action.admin.pos.POSAction.refreshPageAfterUserDetails(POSAction.java:600)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (ThirdPartyPaymentServiceImpl.java:415) - Ajency.in :: DEV :: customer order id is null.
[ INFO] [] [http-nio-8181-exec-29] (21 Jan 2020 11:05:28) (ThirdPartyPaymentServiceImpl.java:417) - Ajency.in :: has pending transactions false for null
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (POSAction.java:2782) - Ajency.in :: payment mode : 600: UPI via EDC Machine
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (POSAction.java:2792) - Ajency.in :: payment mode upi || card || split
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (POSAction.java:2804) - Ajency.in :: creating customer order
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (POSAction.java:5923) - user id:16122943
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (POSAction.java:5924) - user gender:MALE
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (POSAction.java:5933) - Ajency.in :: Invoice email :null
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (POSAction.java:2734) - Ajency.in :: pos cart dto , coupon code: null
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (POSHelper.java:190) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (POSAction.java:3911) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (POSAction.java:3912) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (POSServiceImpl.java:753) - Ajency.in :: updating customer order :null
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (POSServiceImpl.java:764) - Ajency.in :: applied coupon code during creating customer order: null
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (POSAction.java:2814) - Ajency.in :: customer order created id 1236175
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (POSAction.java:2838) - Ajency.in :: final payable  rounded amount :1099.0
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (ThirdPartyPaymentServiceImpl.java:78) - Ajency.in :: customer order id :1236175 transaction id 1236175-1579584999310
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (ThirdPartyPaymentServiceImpl.java:501) - Ajency.in :: transaction number :1236175-1579584999310 amount:109900
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (ThirdPartyPaymentServiceImpl.java:461) - Ajency.in :: fetching pinelabs config for store 4125
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (ThirdPartyPaymentServiceImpl.java:521) - Ajency.in :: pinelabs params {"SecurityToken":"661c9a5f-5d7a-4d76-a950-68beb8225cfd","TransactionNumber":"1236175-1579584999310","AllowedPaymentMode":"10","UserID":15563757,"Amount":109900,"SequenceNumber":1,"MerchantStorePosCode":"04190588","IMEI":"IM239018","MerchantID":2300}
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:39) (ThirdPartyPaymentServiceImpl.java:526) - Ajency.in :: making url call to  https://www.plutuscloudserviceuat.in:8201/API/CloudBasedIntegration/V1/UploadBilledTransaction
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:54) (ThirdPartyPaymentServiceImpl.java:426) - Ajency.in :: openTransactionErrorMessage
[ERROR] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:54) (ThirdPartyPaymentServiceImpl.java:541) - Ajency.in :: Pinelabs api call :1 : DB OPERATION FAILED
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:54) (ThirdPartyPaymentServiceImpl.java:555) - Ajency.in :: pinelabs response {"responseCode":1,"responseMessage":"DB OPERATION FAILED","plutusTransactionReferenceID":-1}
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:54) (ThirdPartyPaymentServiceImpl.java:563) - Ajency.in :: pinelabs api call for transaction 1236175-1579584999310 PlutusTransactionReferenceID:null
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:54) (ThirdPartyPaymentServiceImpl.java:565) - Ajency.in :: messages: 
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:54) (ThirdPartyPaymentServiceImpl.java:96) - Ajency.in :: saved customerOrderTransaction 1005 transactionId :1236175-1579584999310
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:54) (ThirdPartyPaymentServiceImpl.java:99) - Ajency.in :: messages: 
[ INFO] [] [http-nio-8181-exec-28] (21 Jan 2020 11:06:54) (ThirdPartyPaymentServiceImpl.java:417) - Ajency.in :: has pending transactions false for 1236175

`

**Comment by rohan-morje** [comment]
Payment mode selected: UPI

**Comment by rohan-morje** [comment]
Issue resolved

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/72883623-aedf1e00-3d2a-11ea-9531-cf98a8a1d1b4.png)


[ INFO] [] [http-nio-8181-exec-4] (22 Jan 2020 15:02:22) (HkHttpClient.java:290) - Ajency.in :: IO Exception: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.apache.commons.httpclient.AutoCloseInputStream@f51929b; line: 1, column: 2]
[ INFO] [] [http-nio-8181-exec-4] (22 Jan 2020 15:02:22) (HkHttpClient.java:294) - Ajency.in :: IO Exception Stacktrace: org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.apache.commons.httpclient.AutoCloseInputStream@f51929b; line: 1, column: 2]
        at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
        at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2090)
        at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:606)
        at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:492)
        at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2770)
        at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2691)
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1286)
        at org.codehaus.jackson.JsonParser.readValueAs(JsonParser.java:1337)
        at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:268)
        at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:238)
        at com.hk.admin.impl.service.accounting.ThirdPartyPaymentServiceImpl.initiatePinelabsTransaction(ThirdPartyPaymentServiceImpl.java:557)
        at com.hk.admin.impl.service.accounting.ThirdPartyPaymentServiceImpl.initiateTransaction(ThirdPartyPaymentServiceImpl.java:81)
        at com.hk.web.action.admin.pos.POSAction.initiatePayment(POSAction.java:2839)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
        at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
        at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
        at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
        at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
        at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
        at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
        at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
        at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by rohan-morje** [comment]
resolved
