### ISSUE TITLE
"Failed to place order. Please try again after reset." message is displayed when clicked on receive payment button after removing the applied offer for counter cash payment mode.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1232]
Actual result
"Failed to place order. Please try again after reset." message is displayed when clicked on receive payment button after removing the applied offer for counter cash payment mode.

Steps
Enter the details
scan the barcode (Muscleblaze)
select the payment mode as counter cash
Apply an offer
remove the applied offer
click on receive payment

```
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:5954) - user id:5590881
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:5955) - user gender:FEMALE
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:5964) - Ajency.in :: Invoice email :5590881suraj.rathore@brightlifecare.com
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:2732) - Ajency.in :: pos cart dto , coupon code: null
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:3917) - Ajency.in :: IsHKMembership: false skuItem Id: 6543671 skuItem: null
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:3924) - Ajency.in :: updated skuItem: com.hk.domain.sku.SkuItem@49856ef vendor : 2
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSHelper.java:190) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:3942) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:3943) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSServiceImpl.java:753) - Ajency.in :: updating customer order :null
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSServiceImpl.java:764) - Ajency.in :: applied coupon code during creating customer order: null
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:3249) - Ajency.in:: Cart level discount#0.0 for customerOrder#1236315 and user#9999999999#null
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:3282) - Pre-order placement validation passed for user 9999999999#null
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:3294) - Ajency.in:: Total payable amount (Vendor: Bright Lifecare Pvt Ltd) is 2124.5 for user 9999999999#null
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:3313) - Ajency.in:: totalCartPayableExcludeDiscount for order# is 2124.5
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:3322) - Ajency.in:: orderDiscountUnit 0.0
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:3327) - order level flat or percent discount is not applied
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:5445) - Ajency.in:: total payable before applying discount/hkcash for order# 14223817 is 2124.5
[ERROR] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:5459) - Ajency.in:: Offer not applied for order 14223817
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSServiceImpl.java:201) - Ajency.in:: posline items size > 1
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSServiceImpl.java:221) - Ajency.in:: discount amount for pos line item while creating cart line item is #0.0
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSServiceImpl.java:266) - Ajency.in:: discount amount for pos line item after generating cart line item is #0.0
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:3336) - Ajency.in:: order#14223817 created with amount#2124.5
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:3337) - warehosue type:3
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:3338) - trainer Bank Details Id:null
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:3360) - Adding order id 14223817to orders
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (POSAction.java:3397) - Payment created for order#14223817 of user 9999999999#null with amount#2124.5
[ERROR] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (OrderDaoImpl.java:223) - Hibernate trying to save stale Order object whereas the order is placed - 14223817
[ERROR] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:07) (OrderDaoImpl.java:223) - Hibernate trying to save stale Order object whereas the order is placed - 14223817
[ERROR] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:08) (POSServiceImpl.java:337) - Some issue occurred in fetching Taxes for SO: null, line Item: null
[ERROR] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:08) (POSAction.java:3895) - Error ocurred in reverting HK cash for user 9999999999#nullCould not find any history of user point redemption for given user id 5590881 , store id 1 and hk order id 14223817
[ERROR] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:08) (POSAction.java:3475) - Exception occured while creating so for order#14223817 !
java.lang.Exception: Exception occured while creating so line item for so id :null
	at com.hk.admin.impl.service.pos.POSServiceImpl.createSOForStore(POSServiceImpl.java:338)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy177.createSOForStore(Unknown Source)
	at com.hk.web.action.admin.pos.POSAction.receivePaymentAndProcessOrder(POSAction.java:3470)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[ INFO] [] [http-nio-8181-exec-2] (03 Feb 2020 12:53:08) (ThirdPartyPaymentServiceImpl.java:451) - Ajency.in :: has pending transactions false for 1236315

```
![image](https://user-images.githubusercontent.com/54023516/73632295-4f193900-4681-11ea-9897-73f966c0a286.png)

**Comment by shivam-kurtarkar** [comment]
happens when bright is down

**Comment by shivam-kurtarkar** [comment]
message is thrown when exception is thrown while creating so.
