### ISSUE TITLE
Receive payment button,offers,Scan Barcode section, is not displayed when the message "Failed to place order. Please try again after reset." is displayed.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1233]
After issue #1232 occurs the following is noted.

Actual result
Receive payment button,offers,Scan Barcode section, is not displayed when the message "Failed to place order. Please try again after reset." is displayed.

Enter the details
scan the barcode (Muscleblaze)
select the payment mode as counter cash
Apply an offer
remove the applied offer
click on receive payment

![image](https://user-images.githubusercontent.com/54023516/73634004-25aedc00-4686-11ea-98e3-a33268bc0e1a.png)

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/74420531-9c5f8c80-4e71-11ea-892e-331e441f6da6.png)
![image](https://user-images.githubusercontent.com/54023516/74420562-a84b4e80-4e71-11ea-80be-d350e574a1b3.png)
```
FO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:34) (OrderServiceImpl.java:1729) - call updateNetSaleInRedis function starts
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:34) (OrderServiceImpl.java:1735) - Api call completed for function updateNetSaleInRedis URL#-https://api61.healthkartqa.com/api/hkUserLoyalty/updateNetSaleAndLoyaltyLevelForRetailUser?z.ts==1581586174083&st=1
[ INFO] [] [Thread-20] (13 Feb 2020 14:59:34) (MailBoltServiceImpl.java:41) - Ajency.in :: post response null
[ INFO] [] [Thread-20] (13 Feb 2020 14:59:34) (MailBoltServiceImpl.java:43) - Ajency.in :: post response gson 
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:34) (GSTInvoiceDTO.java:110) - Ajency.in:: total line items for invoice > 1
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:34) (GSTInvoiceDTO.java:114) - Ajency.in:: Invoice eligible for clubbing
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:34) (GSTInvoiceDTO.java:159) - Ajency.in:: Product line item for invoice: MuscleBlaze BCAA Pro,  0.99 lb  30 Servings  Watermelon 
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:34) (GSTInvoiceDTO.java:259) - Ajency.in:: LI packmap is empty
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:34) (GSTInvoiceDTO.java:307) - Ajency.in:: Total invoice items > 1
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:34) (GSTInvoiceServiceImpl.java:402) - Ajency.in :: pdf file path : /usr/local/projects/tomcat_aqua_new/webapps/ROOT/gstInvoicePDF/SO_5098677_1581586174124.pdf
[ERROR] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:34) (DigitalSignatureException.java:17) - Error while generating Digital Signature for path: /usr/local/projects/tomcat_aqua_new/webapps/ROOT/gstInvoicePDF/SO_5098677_1581586174124.pdf
java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.hk.admin.util.DigitalSignatureUtil.attachDigitalSignature(DigitalSignatureUtil.java:62)
	at com.hk.admin.util.SOGSTInvoiceGenerator.generateInvoicePDF(SOGSTInvoiceGenerator.java:114)
	at com.hk.admin.impl.service.accounting.GSTInvoiceServiceImpl.generateSOGSTPdf(GSTInvoiceServiceImpl.java:406)
	at com.hk.admin.impl.service.accounting.GSTInvoiceServiceImpl.generateAndUploadInvoice(GSTInvoiceServiceImpl.java:433)
	at com.hk.web.action.admin.pos.POSAction.receivePaymentAndProcessOrder(POSAction.java:3803)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778)
	... 82 more
[ERROR] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:34) (SOGSTInvoiceGenerator.java:116) - java.io.IOException: Keystore was tampered with, or password was incorrect
com.hk.exception.DigitalSignatureException: java.io.IOException: Keystore was tampered with, or password was incorrect
	at com.hk.admin.util.DigitalSignatureUtil.attachDigitalSignature(DigitalSignatureUtil.java:88)
	at com.hk.admin.util.SOGSTInvoiceGenerator.generateInvoicePDF(SOGSTInvoiceGenerator.java:114)
	at com.hk.admin.impl.service.accounting.GSTInvoiceServiceImpl.generateSOGSTPdf(GSTInvoiceServiceImpl.java:406)
	at com.hk.admin.impl.service.accounting.GSTInvoiceServiceImpl.generateAndUploadInvoice(GSTInvoiceServiceImpl.java:433)
	at com.hk.web.action.admin.pos.POSAction.receivePaymentAndProcessOrder(POSAction.java:3803)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.hk.admin.util.DigitalSignatureUtil.attachDigitalSignature(DigitalSignatureUtil.java:62)
	... 77 more
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778)
	... 82 more
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:34) (GSTInvoiceServiceImpl.java:408) - Ajency.in :: new pdf created : /usr/local/projects/tomcat_aqua_new/webapps/ROOT/gstInvoicePDF/SO_5098677_1581586174124.pdf
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:34) (GSTInvoiceServiceImpl.java:435) - Ajency.in :: uploading to s3 with file key: gstInvoicePDF/2020/Feb/SO_5098677_1581586174124.pdf
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:37) (GSTInvoiceServiceImpl.java:440) - Ajency.in :: successfully uploaded to upload pdf to aws gstInvoicePDF/2020/Feb/SO_5098677_1581586174124.pdf
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:37) (GSTInvoiceServiceImpl.java:448) - Ajency.in :: saved to sogstInvoiceHistory table , id:102564
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:37) (POSAction.java:3807) - Ajency.in :: sending link for so 5098677 to customer true from store 4067
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:37) (GSTInvoiceServiceImpl.java:622) - Ajency.in :: user login : manishguptaaa@gmail.com
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:37) (GSTInvoiceServiceImpl.java:631) - Ajency.in :: customer invoice url : http://aqua61.healthkartqa.com/core/accounting/GSTInvoiceDownload.action?customerInvoiceAsPdf=&gatewayOrderId=5098677-S38592&user=Zjb8WpC5Ur8%252B4Z%252Fl0SMlmg%253D%253D
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:37) (GSTInvoiceServiceImpl.java:543) - Ajency.in :: sending email to email address : 5590881suraj.rathore@brightlifecare.com
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:37) (MailBoltServiceImpl.java:68) - Ajency.in :: making mailbolt api call to url :/HKAdminTools/mail/completeMailPush
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:37) (NpsSmsServiceImpl.java:67) - saving particular customer to the npsSmstrigger table9999999999
[ INFO] [] [Thread-21] (13 Feb 2020 14:59:37) (MailBoltServiceImpl.java:75) - Ajency.in :: MAILBOLT :: mailbolt request: {"customParams":{"orderId":"1386521-ST92221","link":"http://aqua61.healthkartqa.com/core/accounting/GSTInvoiceDownload.action?customerInvoiceAsPdf\u003d\u0026gatewayOrderId\u003d5098677-S38592\u0026user\u003dZjb8WpC5Ur8%252B4Z%252Fl0SMlmg%253D%253D","user":"Monica","npsLink":"http://aqua61.healthkartqa.com/pages/feedback.jsp?orderId\u003d1386521-ST92221"},"subject":"Your Healthkart Order no. 1386521-ST92221 GST Invoice","name":"Monica","campaignName":"gst_invoice_email","email":"5590881suraj.rathore@brightlifecare.com"}
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:37) (NpsSmsServiceImpl.java:77) - Saved Data to nps Sms Trigger table
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:37) (GSTInvoiceServiceImpl.java:581) - Ajency.in :: sending link http://aqua61.healthkartqa.com/core/accounting/GSTInvoiceDownload.action?customerInvoiceAsPdf=&gatewayOrderId=5098677-S38592&user=Zjb8WpC5Ur8%252B4Z%252Fl0SMlmg%253D%253D sms to mobile no: 9999999999
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:37) (GSTInvoiceServiceImpl.java:593) - Ajency.in :: making jarvis call for sending sms to the customer [sms_gst_invoice] no:9999999999
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:37) (MailBoltServiceImpl.java:68) - Ajency.in :: making mailbolt api call to url :/HKAdminTools/sms/transactional/send/customParams
[ INFO] [] [Thread-22] (13 Feb 2020 14:59:37) (MailBoltServiceImpl.java:75) - Ajency.in :: MAILBOLT :: mailbolt request: {"sendSms":true,"phoneNumber":"9999999999","customParams":{"orderId":"1386521-ST92221","link":"http://aqua61.healthkartqa.com/core/accounting/GSTInvoiceDownload.action?customerInvoiceAsPdf\u003d\u0026gatewayOrderId\u003d5098677-S38592\u0026user\u003dZjb8WpC5Ur8%252B4Z%252Fl0SMlmg%253D%253D","customerName":"Monica","npsLink":"http://aqua61.healthkartqa.com/pages/feedback.jsp?orderId\u003d1386521-ST92221"},"smsCampaignName":"sms_gst_invoice","userName":"Monica","senderChannel":"HEALTHKART_RETAIL_API"}
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:37) (ThirdPartyPaymentServiceImpl.java:507) - Ajency.in :: has pending transactions false for 1386521
[ INFO] [] [http-nio-8181-exec-7] (13 Feb 2020 14:59:37) (ThirdPartyPaymentServiceImpl.java:520) - Ajency.in :: hasActivePinelabsConfig true store 4067
[ INFO] [] [Thread-21] (13 Feb 2020 14:59:38) (MailBoltServiceImpl.java:78) - Ajency.in :: MAILBOLT :: mailbolt response: {"exception":false,"messages":[]}
[ INFO] [] [Thread-22] (13 Feb 2020 14:59:38) (MailBoltServiceImpl.java:78) - Ajency.in :: MAILBOLT :: mailbolt response: {"exception":false,"messages":[]}
[ INFO] [] [pool-24-thread-1] (13 Feb 2020 15:00:00) (UploadUsersScheduler.java:52) - Ajency.in :: Schedule Upload Users ::  Upload Users Campaign Cron Executed:1581586200000
[ INFO] [] [pool-24-thread-1] (13 Feb 2020 15:00:00) (UploadUsersScheduler.java:68) - Ajency.in :: Schedule Upload Users :: uploadUsersEnableCron : true uploadUsersThreshold : 2000 uploadUsersEmailAddress : analytics@brightlifecare.com,retail.tech@brightlifecare.com uploadUsersCronStartTime : 22:00:00 uploadUsersPerDayLimit : 800
[ INFO] [] [pool-24-thread-1] (13 Feb 2020 15:00:26) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (13 Feb 2020 15:00:26) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false

```

**Comment by shivam-kurtarkar** [comment]
please give steps to replicate

**Comment by shivam-kurtarkar** [comment]
Failed to place order. Please try again after reset. occures when so creating throws exception
