### ISSUE TITLE
After the Paytm voucher is applied the payment mode is set to set to split payment mode.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1235]
Actual result
After the Paytm voucher is applied the payment mode is set to set to split payment mode.

Steps
Go to the POS screen.
Scan a barcode
Click on paytm voucher
apply the voucher TEST107 

![image](https://user-images.githubusercontent.com/54023516/73642520-d2458980-4697-11ea-9469-be16ac689f03.png)
`[ INFO] [] [http-nio-8181-exec-4] (03 Feb 2020 15:13:10) (POSAction.java:1983) - Ajency.in :: FREEBIE-GROUPING :: Retail Warehouse 
[ INFO] [] [http-nio-8181-exec-4] (03 Feb 2020 15:13:10) (ThirdPartyPaymentServiceImpl.java:460) - Ajency.in :: DEV :: customer order id is null.
[ INFO] [] [http-nio-8181-exec-4] (03 Feb 2020 15:13:10) (ThirdPartyPaymentServiceImpl.java:462) - Ajency.in :: has pending transactions false for null
[ INFO] [] [http-nio-8181-exec-12] (03 Feb 2020 15:13:39) (POSAction.java:3917) - Ajency.in :: IsHKMembership: false skuItem Id: 7758651 skuItem: null
[ INFO] [] [http-nio-8181-exec-12] (03 Feb 2020 15:13:39) (POSAction.java:3924) - Ajency.in :: updated skuItem: com.hk.domain.sku.SkuItem@23b78451 vendor : 2
[ INFO] [] [http-nio-8181-exec-12] (03 Feb 2020 15:13:39) (POSHelper.java:190) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-12] (03 Feb 2020 15:13:39) (POSAction.java:3942) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-12] (03 Feb 2020 15:13:39) (POSAction.java:3943) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-12] (03 Feb 2020 15:13:39) (HkHttpClient.java:290) - Ajency.in :: IO Exception: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: org.apache.commons.httpclient.AutoCloseInputStream@53fefb54; line: 1, column: 2]
[ INFO] [] [http-nio-8181-exec-12] (03 Feb 2020 15:13:39) (HkHttpClient.java:294) - Ajency.in :: IO Exception Stacktrace: org.codehaus.jackson.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: org.apache.commons.httpclient.AutoCloseInputStream@53fefb54; line: 1, column: 2]
	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._throwInvalidSpace(JsonParserMinimalBase.java:467)
	at org.codehaus.jackson.impl.Utf8StreamParser._skipWSOrEnd(Utf8StreamParser.java:2322)
	at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:444)
	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2770)
	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2691)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1286)
	at org.codehaus.jackson.JsonParser.readValueAs(JsonParser.java:1337)
	at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:268)
	at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:238)
	at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:205)
	at com.hk.api.edge.integration.impl.service.variant.HkVariantServiceImpl.getOffersForCart(HkVariantServiceImpl.java:78)
	at com.hk.web.action.admin.pos.POSAction.getOffersForCart(POSAction.java:4340)
	at com.hk.web.action.admin.pos.POSAction.getCartOffers(POSAction.java:2555)
	at com.hk.web.action.admin.pos.POSAction.applyPaytmVoucher(POSAction.java:4490)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

[ INFO] [] [http-nio-8181-exec-12] (03 Feb 2020 15:13:39) (ThirdPartyPaymentServiceImpl.java:460) - Ajency.in :: DEV :: customer order id is null.
[ INFO] [] [http-nio-8181-exec-12] (03 Feb 2020 15:13:39) (ThirdPartyPaymentServiceImpl.java:462) - Ajency.in :: has pending transactions false for null
[ INFO] [] [pool-24-thread-1] (03 Feb 2020 15:16:58) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (03 Feb 2020 15:16:58) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false
`

**Comment by shivam-kurtarkar** [comment]
this might be existing functionality
when voucher amount is lesser then total payment mode is changed to split
