### ISSUE TITLE
"Failed to Initiate Transaction, please try again." message is displayed on click of initiate transaction button.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1246]
Actual result
"Failed to Initiate Transaction, please try again." message is displayed on click of initiate transaction button.

Steps
scan a barcode
Enter the details
Click on initiate transaction.
![image](https://user-images.githubusercontent.com/54023516/73648395-7680fd80-46a3-11ea-8feb-4d4ebbd1611c.png)

![image](https://user-images.githubusercontent.com/54023516/73648265-33268f00-46a3-11ea-80a7-adf8bd74e01b.png)

`[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:20) (POSHelper.java:187) - Ajency.in:: postcart dto is null 
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:20) (POSAction.java:3940) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:20) (POSAction.java:3941) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/variant/72367?z.ts==1580727860059&st=1&rtSt=4033&offerPerPage=20&st=1  RC: 200
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (HkHttpClient.java:109) -  http T:0 ms 
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (HkHttpClient.java:129) -  parsing T:44 ms 
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (POSServiceImpl.java:798) - Ajency.in :: fefo enabled true
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (POSServiceImpl.java:805) - Applying fefo discount for variant MuscleBlaze Whey Protein,  4.4 lb  Rich Milk Chocolate 
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (ProductVariantServiceImpl.java:471) - Ajency.in :: NPL FLASH Discount Config true
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (ProductVariantServiceImpl.java:473) - Ajency.in :: flash discount enabled for store
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/sale/flashDeal/0/NUT1367-39?z.ts==1580727865587&st=1  RC: 200
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (HkHttpClient.java:109) -  http T:0 ms 
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (HkHttpClient.java:129) -  parsing T:3 ms 
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (FefoDiscountServiceImpl.java:59) - Ajency.in:: Custom discount applicable for variant MuscleBlaze Whey Protein,  4.4 lb  Rich Milk Chocolate 
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (FefoDiscountServiceImpl.java:198) - Ajency.in:: total discount amount is 3639.3
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (POSHelper.java:103) - Ajency.in:: Adding vendor to poslineitems >= 2
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (POSHelper.java:190) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (POSAction.java:3940) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (POSAction.java:3941) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (POSAction.java:1983) - Ajency.in :: FREEBIE-GROUPING :: Retail Warehouse 
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (ThirdPartyPaymentServiceImpl.java:460) - Ajency.in :: DEV :: customer order id is null.
[ INFO] [] [http-nio-8181-exec-3] (03 Feb 2020 16:34:25) (ThirdPartyPaymentServiceImpl.java:462) - Ajency.in :: has pending transactions false for null
[ERROR] [] [Thread-7] (03 Feb 2020 16:34:27) (Worker.java:520) - Caught exception when initializing LeaseCoordinator
com.amazonaws.services.kinesis.leases.exceptions.DependencyException: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 192.168.70.62:4568 [/192.168.70.62] failed: Connection refused (Connection refused)
	at com.amazonaws.services.kinesis.leases.impl.LeaseManager.createLeaseTableIfNotExists(LeaseManager.java:135)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibLeaseCoordinator.initialize(KinesisClientLibLeaseCoordinator.java:307)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:495)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:436)
	at com.hk.web.listener.KinesisConsumer$1.run(KinesisConsumer.java:90)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 192.168.70.62:4568 [/192.168.70.62] failed: Connection refused (Connection refused)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1114)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1064)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2954)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2930)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeCreateTable(AmazonDynamoDBClient.java:899)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.createTable(AmazonDynamoDBClient.java:874)
	at com.amazonaws.services.kinesis.leases.impl.LeaseManager.createLeaseTableIfNotExists(LeaseManager.java:128)
	... 5 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 192.168.70.62:4568 [/192.168.70.62] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy248.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1236)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory$TrustingSocketFactory.connectSocket(ApacheConnectionManagerFactory.java:184)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 31 more
[ INFO] [] [Thread-7] (03 Feb 2020 16:34:37) (Worker.java:493) - Initialization attempt 3
[ INFO] [] [Thread-7] (03 Feb 2020 16:34:37) (Worker.java:494) - Initializing LeaseCoordinator
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 16:34:38) (POSAction.java:2219) - Ajency.in:: Phone->  9673804372
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 16:34:38) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/user/retail/name/1/9673804372?z.ts==1580727878615&loyaltyEnabled=true&st=1  RC: 200
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 16:34:38) (HkHttpClient.java:109) -  http T:0 ms 
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 16:34:38) (HkHttpClient.java:129) -  parsing T:1 ms 
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 16:34:38) (POSAction.java:2475) - Ajency.in :: DEV :: fetching invoice email from user details
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 16:34:38) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/userPoints/reward/1/35994179/points?z.ts==1580727878921&st=1  RC: 200
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 16:34:38) (HkHttpClient.java:109) -  http T:0 ms 
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 16:34:38) (HkHttpClient.java:129) -  parsing T:1 ms 
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 16:34:39) (POSAction.java:2338) - Ajency.in :: hk user id:35994179
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 16:34:39) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/public/getPersonalizedCouponsForRetailStoreUser/35994179?z.ts==1580727879115&st=1&rstId=4033&st=1  RC: 200
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 16:34:39) (HkHttpClient.java:109) -  http T:0 ms 
[ INFO] [] [http-nio-8181-exec-10] (03 Feb 2020 16:34:39) (HkHttpClient.java:129) -  parsing T:1 ms 
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (POSAction.java:3915) - Ajency.in :: IsHKMembership: false skuItem Id: 5869779 skuItem: null
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (POSAction.java:3922) - Ajency.in :: updated skuItem: com.hk.domain.sku.SkuItem@3b75f70d vendor : 2
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (POSHelper.java:190) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (POSAction.java:3940) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (POSAction.java:3941) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (POSServiceImpl.java:798) - Ajency.in :: fefo enabled true
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (POSServiceImpl.java:978) - Ajency.in :: existing product variant found
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (POSServiceImpl.java:979) - Ajency.in :: flash discount applied 70.0
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (POSServiceImpl.java:805) - Applying fefo discount for variant MuscleBlaze Whey Protein,  4.4 lb  Rich Milk Chocolate 
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (ProductVariantServiceImpl.java:471) - Ajency.in :: NPL FLASH Discount Config true
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (ProductVariantServiceImpl.java:473) - Ajency.in :: flash discount enabled for store
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/sale/flashDeal/0/NUT1367-39?z.ts==1580727880324&st=1  RC: 200
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (HkHttpClient.java:109) -  http T:0 ms 
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (HkHttpClient.java:129) -  parsing T:2 ms 
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (FefoDiscountServiceImpl.java:59) - Ajency.in:: Custom discount applicable for variant MuscleBlaze Whey Protein,  4.4 lb  Rich Milk Chocolate 
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (FefoDiscountServiceImpl.java:198) - Ajency.in:: total discount amount is 3639.3
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (POSHelper.java:190) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (HkVariantServiceImpl.java:129) - Ajency.in :: POS OFFER INVENTORY CHECK ::  No Variant On Action 215 order level discount flat M
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (HkVariantServiceImpl.java:88) - Ajency.in :: POS OFFER INVENTORY CHECK :: Offer Valid after inventory check 
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (HkVariantServiceImpl.java:129) - Ajency.in :: POS OFFER INVENTORY CHECK ::  No Variant On Action 40 perc itm lvl dics on mrp
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (HkVariantServiceImpl.java:88) - Ajency.in :: POS OFFER INVENTORY CHECK :: Offer Valid after inventory check 
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (HkVariantServiceImpl.java:129) - Ajency.in :: POS OFFER INVENTORY CHECK ::  No Variant On Action 102 order lvl disc flat MB
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (HkVariantServiceImpl.java:88) - Ajency.in :: POS OFFER INVENTORY CHECK :: Offer Valid after inventory check 
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (HkVariantServiceImpl.java:143) - Ajency.in :: POS OFFER INVENTORY CHECK :: VARIANT ID NUT4338-03
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (HkVariantServiceImpl.java:92) - Ajency.in :: POS OFFER INVENTORY CHECK :: Offer not Valid after inventory check 
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (ThirdPartyPaymentServiceImpl.java:460) - Ajency.in :: DEV :: customer order id is null.
[ INFO] [] [http-nio-8181-exec-9] (03 Feb 2020 16:34:40) (ThirdPartyPaymentServiceImpl.java:462) - Ajency.in :: has pending transactions false for null

`

**Comment by shivam-kurtarkar** [comment]
logs does not contain any the calls info
ambiguous
probably transaction was open 
now will show open transaction message
