### ISSUE TITLE
Exception is displayed on the logs when the barcode is scanned, and the initiate transaction button is clicked.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1281]
Actual result
Exception is displayed on the logs when the barcode is scanned, and the initiate transaction button is clicked.

Steps
Go to the POS screen 
Scan the barcode
Enter the details
Select the split  payment mode 
select PayU payment mode
Click on initiate transaction 

`[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:13:47) (HkHttpClient.java:109) -  http T:0 ms 
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:13:47) (HkHttpClient.java:129) -  parsing T:40 ms 
[ INFO] [] [http-nio-8181-exec-10] (05 Feb 2020 18:13:48) (POSHelper.java:190) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-10] (05 Feb 2020 18:13:48) (POSAction.java:3951) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-10] (05 Feb 2020 18:13:48) (POSAction.java:3952) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-10] (05 Feb 2020 18:13:48) (ThirdPartyPaymentServiceImpl.java:471) - Ajency.in :: DEV :: customer order id is null.
[ INFO] [] [http-nio-8181-exec-10] (05 Feb 2020 18:13:48) (ThirdPartyPaymentServiceImpl.java:473) - Ajency.in :: has pending transactions false for null
[ INFO] [] [http-nio-8181-exec-10] (05 Feb 2020 18:13:48) (ThirdPartyPaymentServiceImpl.java:486) - Ajency.in :: hasActivePinelabsConfig true store 4033
[ WARN] [] [http-nio-8181-exec-1] (05 Feb 2020 18:13:52) (Log.java:94) - Unhandled exception caught by the Stripes default exception handler.
javax.servlet.ServletException: Filtered request failed.
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:384)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.shiro.session.InvalidSessionException: java.lang.IllegalStateException: getAttribute: Session already invalidated
	at org.apache.shiro.web.session.HttpServletSession.getAttribute(HttpServletSession.java:148)
	at org.apache.shiro.session.ProxiedSession.getAttribute(ProxiedSession.java:121)
	at org.apache.shiro.subject.support.DelegatingSubject.getRunAsPrincipalsStack(DelegatingSubject.java:469)
	at org.apache.shiro.subject.support.DelegatingSubject.getPrincipals(DelegatingSubject.java:153)
	at org.apache.shiro.subject.support.DelegatingSubject.getPrincipal(DelegatingSubject.java:149)
	at com.hk.impl.service.core.UserServiceImpl.getPrincipal(UserServiceImpl.java:203)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.hk.aop.BusinessMethodTimeProfiler.profile(BusinessMethodTimeProfiler.java:28)
	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy97.getPrincipal(Unknown Source)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	... 32 more
Caused by: java.lang.IllegalStateException: getAttribute: Session already invalidated
	at org.apache.catalina.session.StandardSession.getAttribute(StandardSession.java:1178)
	at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:103)
	at org.apache.shiro.web.session.HttpServletSession.getAttribute(HttpServletSession.java:146)
	... 74 more
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:54) (AjaxAPIResource.java:307) - Ajency.in :: payu 
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:54) (PayuServiceImpl.java:145) - Ajency.in :: transaction number :1236356-1580903768327
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:54) (PayuServiceImpl.java:430) - Ajency.in :: fetching payu config for store 4033
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:54) (PayuServiceImpl.java:434) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@1e534e5d
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:54) (PayuServiceImpl.java:438) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@1e534e5d qrid:STQI-IM4033o1-136227
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:54) (PayuServiceImpl.java:171) - Ajency.in :: injecting incorrect hash value c8aa5dc5f2139936227bc1daf21dd2cad79fc32a623b66098667e6ebfc0f7aec0005f4e19e4296c79cf1f92077db60a20635a572342f5377972c469137db6b
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:54) (PayuServiceImpl.java:186) - Ajency.in :: making url call to  https://mobiletest.payu.in/merchant/postservice.php
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:54) (PayuApiRequest.java:59) - data : vDy3i7|check_bqr_txn_status|1236356-1580903768327|ozyEFwfA
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:54) (PayuApiRequest.java:60) - hash : 9137ff16ac3e2926a362e99d6097a76b572391c99d26a048be60069d37d677cb5d7ff1de85d04c36c53e23798f4a0d9631b73a351a30f18b03d174891878857c
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:54) (PayuApiRequest.java:121) - Ajency.in :: injecting incorrect hash value c8aa5dc5f2139936227bc1daf21dd2cad79fc32a623b66098667e6ebfc0f7aec0005f4e19e4296c79cf1f92077db60a20635a572342f5377972c469137db6b
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:54) (PayuServiceImpl.java:464) - post data to payu gateway: key=vDy3i7&command=check_bqr_txn_status&hash=c8aa5dc5f2139936227bc1daf21dd2cad79fc32a623b66098667e6ebfc0f7aec0005f4e19e4296c79cf1f92077db60a20635a572342f5377972c469137db6b&var1=1236356-1580903768327
[ INFO] [] [http-nio-8181-exec-3] (05 Feb 2020 18:13:54) (ThirdPartyPaymentServiceImpl.java:471) - Ajency.in :: DEV :: customer order id is null.
[ INFO] [] [http-nio-8181-exec-3] (05 Feb 2020 18:13:54) (ThirdPartyPaymentServiceImpl.java:473) - Ajency.in :: has pending transactions false for null
[ INFO] [] [http-nio-8181-exec-3] (05 Feb 2020 18:13:54) (ThirdPartyPaymentServiceImpl.java:486) - Ajency.in :: hasActivePinelabsConfig true store 4033
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:55) (PayuServiceImpl.java:482) - Ajency.in :: retval a:2:{s:6:"status";i:0;s:3:"msg";s:13:"Invalid Hash.";}
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:55) (PayuServiceImpl.java:493) - Ajency.in :: json parsing error  
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:55) (PayuServiceImpl.java:529) - Ajency.in :: result:{"status":{"value":0,"type":3},"msg":{"value":"Invalid Hash.","type":8}}
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:55) (PayuServiceImpl.java:531) - Ajency.in :: status:0
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:55) (PayuServiceImpl.java:532) - Ajency.in :: status:0
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:55) (PayuServiceImpl.java:533) - Ajency.in :: msg:Invalid Hash.
[ERROR] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:55) (PayuServiceImpl.java:578) - Ajency.in :: Payu api call error 0 Invalid Hash.
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:55) (PayuServiceImpl.java:514) - {"map":{}}
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:55) (PayuServiceImpl.java:217) - Ajency.in :: payu response {"map":{}}
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:55) (PayuServiceImpl.java:224) - Ajency.in :: payu api call for transaction 1236356-1580903768327
[ INFO] [] [http-nio-8181-exec-7] (05 Feb 2020 18:13:55) (PayuServiceImpl.java:225) - Ajency.in :: messages: 
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:05) (POSAction.java:1773) - Ajency.in :: NUT CONVERSION :: No ProductVariantConversionDetails found.
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/variant/71652?z.ts==1580906645406&st=1&rtSt=4033&offerPerPage=20&st=1  RC: 200
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (HkHttpClient.java:109) -  http T:0 ms 
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (HkHttpClient.java:129) -  parsing T:59 ms 
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/variant/71652?z.ts==1580906646205&st=1&rtSt=4033&offerPerPage=20&st=1  RC: 200
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (HkHttpClient.java:109) -  http T:0 ms 
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (HkHttpClient.java:129) -  parsing T:5 ms 
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (POSServiceImpl.java:798) - Ajency.in :: fefo enabled true
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (POSServiceImpl.java:805) - Applying fefo discount for variant Cellucor C4 Explosive Preworkout,  0.85 lb  Fruit Punch 
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (ProductVariantServiceImpl.java:471) - Ajency.in :: NPL FLASH Discount Config true
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (FefoDiscountServiceImpl.java:75) - Ajency.in:: Brand discount applicable for variant Cellucor C4 Explosive Preworkout,  0.85 lb  Fruit Punch 
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (FefoDiscountServiceImpl.java:190) - Ajency.in:: fefo discount Applied for barcode#Cellucor C4 Explosive Preworkout,  0.85 lb  Fruit Punch  = 20.0
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (FefoDiscountServiceImpl.java:198) - Ajency.in:: total discount amount is 899.8
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (POSHelper.java:103) - Ajency.in:: Adding vendor to poslineitems >= 1
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (POSHelper.java:190) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (POSAction.java:3951) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (POSAction.java:3952) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (HkVariantServiceImpl.java:129) - Ajency.in :: POS OFFER INVENTORY CHECK ::  No Variant On Action Extra 10% off on Site Wide
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (HkVariantServiceImpl.java:88) - Ajency.in :: POS OFFER INVENTORY CHECK :: Offer Valid after inventory check 
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (POSAction.java:1988) - Ajency.in :: FREEBIE-GROUPING :: Retail Warehouse 
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (ThirdPartyPaymentServiceImpl.java:471) - Ajency.in :: DEV :: customer order id is null.
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (ThirdPartyPaymentServiceImpl.java:473) - Ajency.in :: has pending transactions false for null
[ INFO] [] [http-nio-8181-exec-4] (05 Feb 2020 18:14:06) (ThirdPartyPaymentServiceImpl.java:486) - Ajency.in :: hasActivePinelabsConfig true store 4033
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSAction.java:2792) - Ajency.in :: payment mode : 220: Split Payment
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSAction.java:2803) - Ajency.in :: payment mode upi || card || split
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSAction.java:2815) - Ajency.in :: creating customer order
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSAction.java:5963) - user id:5590881
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSAction.java:5964) - user gender:FEMALE
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSAction.java:5973) - Ajency.in :: Invoice email :5590881suraj.rathore@brightlifecare.com
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSAction.java:2737) - Ajency.in :: pos cart dto , coupon code: null
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSAction.java:3926) - Ajency.in :: IsHKMembership: false skuItem Id: 7556911 skuItem: null
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSAction.java:3933) - Ajency.in :: updated skuItem: com.hk.domain.sku.SkuItem@50ea07fb vendor : 1
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSHelper.java:190) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSAction.java:3951) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSAction.java:3952) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSServiceImpl.java:753) - Ajency.in :: updating customer order :null
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSServiceImpl.java:764) - Ajency.in :: applied coupon code during creating customer order: null
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSAction.java:2825) - Ajency.in :: customer order created id 1236364
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (POSAction.java:2881) - Ajency.in:: splitPaymentSelectedIndex: 0
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (ThirdPartyPaymentServiceImpl.java:59) - Ajency.in :: customer order id :1236364 transaction id 1236364-1580906675654
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (PayuServiceImpl.java:80) - Ajency.in :: transaction number :1236364-1580906675654 amount:300000
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (PayuServiceImpl.java:430) - Ajency.in :: fetching payu config for store 4033
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (PayuServiceImpl.java:434) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@3fc5e5bb
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (PayuServiceImpl.java:438) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@3fc5e5bb qrid:STQI-IM4033o1-136227
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (PayuServiceImpl.java:105) - Ajency.in :: making url call to   https://mobiletest.payu.in/QrPayment
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (PayuApiRequest.java:81) - data : vDy3i7|1236364-1580906675654|300000|Integrated Static QR|||3600|STQI-IM4033o1-136227|||||||||ozyEFwfA
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (PayuApiRequest.java:82) - hash : 7616f221f024c371a765370750dc7cbce6b999ac750829467359e853aeabe290be2cfd1a8e06840be377102919889dea927b60b611de57e1cefcabc2aff96eb0
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:35) (PayuServiceImpl.java:464) - post data to payu gateway: key=vDy3i7&hash=7616f221f024c371a765370750dc7cbce6b999ac750829467359e853aeabe290be2cfd1a8e06840be377102919889dea927b60b611de57e1cefcabc2aff96eb0&txnid=1236364-1580906675654&amount=300000&productinfo=Integrated+Static+QR&expiryTime=3600&qrId=STQI-IM4033o1-136227
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:36) (PayuServiceImpl.java:482) - Ajency.in :: retval {"status":"success","message":"Payment initiated successfully."}
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:36) (PayuServiceImpl.java:496) - Ajency.in :: json parsing error  
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:36) (PayuServiceImpl.java:506) - Ajency.in :: serialized parsing error  
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:36) (PayuServiceImpl.java:514) - 
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:36) (PayuServiceImpl.java:132) - Ajency.in :: payu response 
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:36) (PayuServiceImpl.java:139) - Ajency.in :: payu api call for transaction 1236364-1580906675654
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:36) (PayuServiceImpl.java:140) - Ajency.in :: messages: 
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:36) (ThirdPartyPaymentServiceImpl.java:94) - Ajency.in :: saved customerOrderTransaction 1336 transactionId :1236364-1580906675654
[ERROR] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:36) (POSAction.java:2902) - Ajency.in :: logging error
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:36) (ThirdPartyPaymentServiceImpl.java:473) - Ajency.in :: has pending transactions false for 1236364
[ INFO] [] [http-nio-8181-exec-5] (05 Feb 2020 18:14:36) (ThirdPartyPaymentServiceImpl.java:486) - Ajency.in :: hasActivePinelabsConfig true store 4033

`

**Comment by shivam-kurtarkar** [comment]
exception is related to login.
