### ISSUE TITLE
"Product Variant Barcode" textbox is uneditable.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1317]
Actual result
"Product Variant Barcode" textbox is uneditable.

Steps
Go to HK.com screen
Go to the checkout page  for delivery by sm
change the status of the order to 2000
Scan the barcode
select the payement mode as payu
Click on initiate transaction
change the status to 3
Click on get payment status
Cancel the transaction from postman.
`[ INFO] [] [http-nio-8181-exec-1] (10 Feb 2020 16:58:02) (PayuApiRequest.java:118) - Ajency.in :: not injecting hash value null
[ INFO] [] [http-nio-8181-exec-1] (10 Feb 2020 16:58:02) (PayuServiceImpl.java:472) - post data to payu gateway: key=vDy3i7&command=cancel_qr_payment&hash=50471208d92d53fe3516155de623f480a8825564d3376de996b66efd84676b412f86ea357ed1321365120fbf1f431f99b6f06af030fd19cfc00e6d267bb46139&var1=%7B%22transactionId%22%3A%221384453-1581333907451%22%7D
[ INFO] [] [http-nio-8181-exec-1] (10 Feb 2020 16:58:03) (PayuServiceImpl.java:490) - Ajency.in :: retval {"status":"success","message":"Cancellation Successful"}
[ INFO] [] [http-nio-8181-exec-1] (10 Feb 2020 16:58:03) (PayuServiceImpl.java:506) - Ajency.in :: json parsing failed, trying to un-serialize postdata:key=vDy3i7&command=cancel_qr_payment&hash=50471208d92d53fe3516155de623f480a8825564d3376de996b66efd84676b412f86ea357ed1321365120fbf1f431f99b6f06af030fd19cfc00e6d267bb46139&var1=%7B%22transactionId%22%3A%221384453-1581333907451%22%7D
[ INFO] [] [http-nio-8181-exec-1] (10 Feb 2020 16:58:03) (PayuServiceImpl.java:519) - Ajency.in :: failed to un-serialize  postdata:key=vDy3i7&command=cancel_qr_payment&hash=50471208d92d53fe3516155de623f480a8825564d3376de996b66efd84676b412f86ea357ed1321365120fbf1f431f99b6f06af030fd19cfc00e6d267bb46139&var1=%7B%22transactionId%22%3A%221384453-1581333907451%22%7D
[ERROR] [] [http-nio-8181-exec-1] (10 Feb 2020 16:58:03) (PayuServiceImpl.java:528) - Ajency.in :: parsing exception for postdata:key=vDy3i7&command=cancel_qr_payment&hash=50471208d92d53fe3516155de623f480a8825564d3376de996b66efd84676b412f86ea357ed1321365120fbf1f431f99b6f06af030fd19cfc00e6d267bb46139&var1=%7B%22transactionId%22%3A%221384453-1581333907451%22%7D
[ INFO] [] [http-nio-8181-exec-1] (10 Feb 2020 16:58:03) (PayuServiceImpl.java:533) - {"status":"success","message":"Cancellation Successful","map":{}}
[ INFO] [] [http-nio-8181-exec-1] (10 Feb 2020 16:58:03) (PayuServiceImpl.java:283) - Ajency.in :: payu response {"status":"success","message":"Cancellation Successful","map":{}}
[ INFO] [] [http-nio-8181-exec-1] (10 Feb 2020 16:58:03) (PayuServiceImpl.java:293) - Ajency.in :: payu api call for transaction 1384453-1581333907451
[ INFO] [] [http-nio-8181-exec-1] (10 Feb 2020 16:58:03) (PayuServiceImpl.java:294) - Ajency.in :: messages: 
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (POSAction.java:3082) - Ajency.in :: order count:0
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (POSAction.java:3090) - Ajency.in :: Customer Order Transaction Id11
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (ThirdPartyPaymentServiceImpl.java:265) - Ajency.in :: cancelling transaction, id:11
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (ThirdPartyPaymentServiceImpl.java:125) - Ajency.in :: user 16067491 customerOrder Transcation id 11
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (ThirdPartyPaymentServiceImpl.java:129) - Ajency.in :: payu get status ...3
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (ThirdPartyPaymentServiceImpl.java:170) - Ajency.in :: payu getting status from db..
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (ThirdPartyPaymentServiceImpl.java:215) - Ajency.in :: customer
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (ThirdPartyPaymentServiceImpl.java:309) - Ajency.in :: transaction already succeded, making a void call id:11
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (ThirdPartyPaymentServiceImpl.java:310) - Ajency.in :: making void api call for transaction id (mihpayid/ptrid):null
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (ThirdPartyPaymentServiceImpl.java:318) - Ajency.in :: customer order transaction id :11 refundTransactionNumber Ref11-1581334094431
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:300) - Ajency.in :: transaction number :1384453-1581333907451 refundTransactionNumber:Ref11-1581334094431 transactinoAmount:89900 mihpayid:null
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:438) - Ajency.in :: fetching payu config for store 4067
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:442) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@6660e11d
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:446) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@6660e11d qrid:STQI-4067-136227
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:327) - Ajency.in :: making url call to  https://mobiletest.payu.in/merchant/postservice.php
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuApiRequest.java:53) - data : vDy3i7|cancel_refund_transaction|null|ozyEFwfA
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuApiRequest.java:54) - hash : f9ad600df8350c094d45018d5e64d8dc8caf847bc7c74714f6d3a1ade98cb30fbfa3b63d8a6552abf61335f338e9bfd175e06c34dd2e30ebf466e192ff0331aa
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuApiRequest.java:118) - Ajency.in :: not injecting hash value null
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuApiRequest.java:169) - Ajency.in :: Exception occurred while url encoding
java.lang.NullPointerException
	at java.net.URLEncoder.encode(URLEncoder.java:204)
	at com.hk.rest.request.thirdPartyPayment.PayuApiRequest.addQueryParam(PayuApiRequest.java:166)
	at com.hk.rest.request.thirdPartyPayment.PayuApiRequest.PostData(PayuApiRequest.java:129)
	at com.hk.admin.impl.service.accounting.thirdParty.PayuServiceImpl.voidPayuTransaction(PayuServiceImpl.java:328)
	at com.hk.admin.impl.service.accounting.ThirdPartyPaymentServiceImpl.cancelTransaction(ThirdPartyPaymentServiceImpl.java:321)
	at com.hk.web.action.admin.pos.POSAction.cancelPayment(POSAction.java:3094)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:472) - post data to payu gateway: key=vDy3i7&command=cancel_refund_transaction&hash=f9ad600df8350c094d45018d5e64d8dc8caf847bc7c74714f6d3a1ade98cb30fbfa3b63d8a6552abf61335f338e9bfd175e06c34dd2e30ebf466e192ff0331aa&var2=Ref11-1581334094431&var3=89900
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:490) - Ajency.in :: retval a:2:{s:6:"status";i:0;s:3:"msg";s:13:"Invalid Hash.";}
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:506) - Ajency.in :: json parsing failed, trying to un-serialize postdata:key=vDy3i7&command=cancel_refund_transaction&hash=f9ad600df8350c094d45018d5e64d8dc8caf847bc7c74714f6d3a1ade98cb30fbfa3b63d8a6552abf61335f338e9bfd175e06c34dd2e30ebf466e192ff0331aa&var2=Ref11-1581334094431&var3=89900
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:548) - Ajency.in :: result:{"status":{"value":0,"type":3},"msg":{"value":"Invalid Hash.","type":8}}
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:550) - Ajency.in :: status:0
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:551) - Ajency.in :: status:0
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:552) - Ajency.in :: msg:Invalid Hash.
[ERROR] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:597) - Ajency.in :: Payu api call error 0 Invalid Hash.
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:519) - Ajency.in :: failed to un-serialize  postdata:key=vDy3i7&command=cancel_refund_transaction&hash=f9ad600df8350c094d45018d5e64d8dc8caf847bc7c74714f6d3a1ade98cb30fbfa3b63d8a6552abf61335f338e9bfd175e06c34dd2e30ebf466e192ff0331aa&var2=Ref11-1581334094431&var3=89900
[ERROR] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:528) - Ajency.in :: parsing exception for postdata:key=vDy3i7&command=cancel_refund_transaction&hash=f9ad600df8350c094d45018d5e64d8dc8caf847bc7c74714f6d3a1ade98cb30fbfa3b63d8a6552abf61335f338e9bfd175e06c34dd2e30ebf466e192ff0331aa&var2=Ref11-1581334094431&var3=89900
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:533) - {"map":{}}
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:360) - Ajency.in :: payu response {"map":{}}
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:369) - Ajency.in :: payu api call for transaction 1384453-1581333907451
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (PayuServiceImpl.java:370) - Ajency.in :: messages: 
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (POSAction.java:3098) - Ajency.in :: pos action transaction status :SUCCESS
[ERROR] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (POSAction.java:3107) - Ajency.in :: Error occured when cancelling order status:3
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (ThirdPartyPaymentServiceImpl.java:474) - Ajency.in :: has pending transactions true
[ INFO] [] [http-nio-8181-exec-11] (10 Feb 2020 16:58:14) (ThirdPartyPaymentServiceImpl.java:497) - Ajency.in :: hasActivePinelabsConfig false store 4067
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (HKOrderAction.java:640) - Ajency.in :: HK CHECKOUT
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (DSRServiceImpl.java:1189) - Ajency.in :: POS :: pos dsr dateStringList: [2020-02-09, 2020-02-08, 2020-02-07, 2020-02-06, 2020-02-05] for wh: 4083
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (DSRServiceImpl.java:1201) - Ajency.in :: POS :: dsr missing dates: [2020-02-09, 2020-02-08, 2020-02-07, 2020-02-06, 2020-02-05] for wh: 4083
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (DSRServiceImpl.java:120) - Ajency.in :: DSR :: warehouse: 4083 startDate: Fri Feb 07 00:00:00 IST 2020 endDate: Sun Feb 09 23:59:59 IST 2020 posSalesList: 0
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (POSReportServiceImpl.java:206) - Ajency.in :: TOTAL POS COUNT 0 TOTAL HK COUNT 0
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (POSReportServiceImpl.java:209) - Ajency.in :: TOTAL COUNT 0
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (HkHttpClient.java:98) - https://api61.healthkartqa.com/api/order/payAtStoreCollection?z.ts==1581334099758&st=1&rsPrefix=TKV&startDate=2020-02-07&endDate=2020-02-09  RC: 200
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (HkHttpClient.java:109) -  http T:0 ms 
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (HkHttpClient.java:129) -  parsing T:2 ms 
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (DSRServiceImpl.java:157) - Ajency.in :: DSR :: warehouse: 4083 startDate: Fri Feb 07 00:00:00 IST 2020 endDate: Sun Feb 09 23:59:59 IST 2020 hk returns size: 0
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (DSRServiceImpl.java:162) - Ajency.in :: DSR :: warehouse: 4083 startDate: Fri Feb 07 00:00:00 IST 2020 endDate: Sun Feb 09 23:59:59 IST 2020 hk sales size: 0
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (DSRServiceImpl.java:1075) - Ajency.in :: DSR :: prepaid = 0.0 cash collected = 0.0
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (DSRServiceImpl.java:1113) - Ajency.in :: DSR :: cash refunded = 0.0
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (BankingDataServiceImpl.java:73) - Ajency.in :: DSR :: warehouse: 4083 startDate: Fri Feb 07 00:00:00 IST 2020 endDate: Sun Feb 09 23:59:59 IST 2020 pos cash: 0.0
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (BankingDataServiceImpl.java:77) - Ajency.in :: DSR :: warehouse: 4083 startDate: Fri Feb 07 00:00:00 IST 2020 endDate: Sun Feb 09 23:59:59 IST 2020 pas cash: 0.0
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (BankingDataServiceImpl.java:81) - Ajency.in :: DSR :: warehouse: 4083 startDate: Fri Feb 07 00:00:00 IST 2020 endDate: Sun Feb 09 23:59:59 IST 2020 hk cash: 0.0
[ INFO] [] [http-nio-8181-exec-35] (10 Feb 2020 16:58:19) (BankingDataServiceImpl.java:85) - Ajency.in :: DSR :: warehouse: 4083 startDate: Fri Feb 07 00:00:00 IST 2020 endDate: Sun Feb 09 23:59:59 IST 2020 total cash collection: 0.0
[ INFO] [] [http-nio-8181-exec-66] (10 Feb 2020 16:58:20) (POSAction.java:577) - Ajency.in:: state name is MAHARASHTRA
[ INFO] [] [http-nio-8181-exec-66] (10 Feb 2020 16:58:20) (ThirdPartyPaymentServiceImpl.java:474) - Ajency.in :: has pending transactions true
[ INFO] [] [http-nio-8181-exec-66] (10 Feb 2020 16:58:20) (ThirdPartyPaymentServiceImpl.java:497) - Ajency.in :: hasActivePinelabsConfig false store 4067
[ INFO] [] [pool-24-thread-1] (10 Feb 2020 16:59:27) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (10 Feb 2020 16:59:27) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false
[ INFO] [] [pool-24-thread-1] (10 Feb 2020 17:00:00) (UploadUsersScheduler.java:52) - Ajency.in :: Schedule Upload Users ::  Upload Users Campaign Cron Executed:1581334200000
[ INFO] [] [pool-24-thread-1] (10 Feb 2020 17:00:00) (UploadUsersScheduler.java:68) - Ajency.in :: Schedule Upload Users :: uploadUsersEnableCron : true uploadUsersThreshold : 2000 uploadUsersEmailAddress : analytics@brightlifecare.com,retail.tech@brightlifecare.com uploadUsersCronStartTime : 22:00:00 uploadUsersPerDayLimit : 800
[ INFO] [] [pool-24-thread-1] (10 Feb 2020 17:04:27) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (10 Feb 2020 17:04:27) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false
`
![image](https://user-images.githubusercontent.com/54023516/74146607-747ce880-4c27-11ea-98a0-81591a7f2b34.png)

**Comment by sharangsamonkar** [comment]
@larissa-c-d  Please provide proper steps of replication.

**Comment by shivam-kurtarkar** [comment]
1. transaction in db is success
2. when you do get status since it is success api call not made
3. irrespective of manual cancel it will call void call

product variant barcode field is disabled because there is transaction against it (in success state)

**Comment by larissa-c-d** [comment]
occurs when the transaction is open, for the order
