### ISSUE TITLE
"java.io.IOException: Server returned HTTP response code: 500" is displayed in the logs on click of initiate payment .

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1325]
Actual result
"java.io.IOException: Server returned HTTP response code: 500" is displayed in the logs on click of initiate payment .

Steps 
Go to hk.com checkout page
Select the payment mode split
select payu payment mode
Click on initiate transaction

![image](https://user-images.githubusercontent.com/54023516/74214266-c161cd00-4cc2-11ea-8a38-7ac17948eb48.png)

```
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (POSAction.java:2800) - Ajency.in :: payment mode : 220: Split Payment
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (POSAction.java:2811) - Ajency.in :: payment mode upi || card || split
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (POSAction.java:2819) - Ajency.in :: trying to fetch customer order by id :1384437
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (POSAction.java:2842) - Ajency.in :: order count:0
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (POSAction.java:2892) - Ajency.in:: splitPaymentSelectedIndex: 0
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (ThirdPartyPaymentServiceImpl.java:59) - Ajency.in :: customer order id :1384437 transaction id 1384437-1581401049502
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (PayuServiceImpl.java:82) - Ajency.in :: transaction number :1384437-1581401049502 amount:100000
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (PayuServiceImpl.java:445) - Ajency.in :: fetching payu config for store 4213
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (PayuServiceImpl.java:449) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@2a282309
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (PayuServiceImpl.java:453) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@2a282309 qrid:STQI-4213-136227
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (PayuServiceImpl.java:106) - Ajency.in :: making url call to   https://mobiletest.payu.in/QrPayment
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (PayuApiRequest.java:75) - data : vDy3i7|1384437-1581401049502|100000|Integrated Static QR|||3600|STQI-4213-136227|||||||||ozyEFwfA
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (PayuApiRequest.java:76) - hash : f9739e203dd83f17ba28320997c2d38716c88e629910fd351e338a980892611b95f3f033b88fed31aaa2f082f823a61c83b3e4839296e72d5d45ea9657ce7d71
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (PayuServiceImpl.java:479) - post data to payu gateway: key=vDy3i7&hash=f9739e203dd83f17ba28320997c2d38716c88e629910fd351e338a980892611b95f3f033b88fed31aaa2f082f823a61c83b3e4839296e72d5d45ea9657ce7d71&txnid=1384437-1581401049502&amount=100000&productinfo=Integrated+Static+QR&expiryTime=3600&qrId=STQI-4213-136227
[ERROR] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (PayuServiceImpl.java:550) - Exception occurred 
java.io.IOException: Server returned HTTP response code: 500 for URL: https://mobiletest.payu.in/QrPayment
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at com.hk.admin.impl.service.accounting.thirdParty.PayuServiceImpl.makePayURequest(PayuServiceImpl.java:490)
	at com.hk.admin.impl.service.accounting.thirdParty.PayuServiceImpl.initiatePayuTransaction(PayuServiceImpl.java:107)
	at com.hk.admin.impl.service.accounting.ThirdPartyPaymentServiceImpl.initiateTransaction(ThirdPartyPaymentServiceImpl.java:72)
	at com.hk.web.action.admin.pos.POSAction.initiatePayment(POSAction.java:2903)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (PayuServiceImpl.java:135) - Ajency.in :: payu response 
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (PayuServiceImpl.java:142) - Ajency.in :: payu api call for transaction 1384437-1581401049502
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (PayuServiceImpl.java:143) - Ajency.in :: messages: Error occurred, cannot initiate transaction
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (ThirdPartyPaymentServiceImpl.java:74) - Ajency.in :: payudto status :null
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (ThirdPartyPaymentServiceImpl.java:96) - Ajency.in :: saved customerOrderTransaction 46 transactionId :1384437-1581401049502
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (POSAction.java:2912) - Ajency.in :: pos action transaction status :FAILED
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (ThirdPartyPaymentServiceImpl.java:486) - Ajency.in :: has pending transactions false for 1384437
[ INFO] [] [http-nio-8181-exec-11] (11 Feb 2020 11:34:09) (ThirdPartyPaymentServiceImpl.java:499) - Ajency.in :: hasActivePinelabsConfig true store 4213
```

**Comment by shivam-kurtarkar** [comment]
payu server was down hence gave 500 response
