### ISSUE TITLE
Response not fetched on click of get status.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1327]
Actual result
Response not fetched on click of get status.

Expected result
Response should be fetched on click of get status.

Steps
Check the status in postman https://aqua61.healthkartqa.com/rest/api/ajax/payu/getstatus/1386485-1581398444741

`from <a href='/admin/payment/OpenTransactionUi.action' target='_blank'>Open Transaction</a> / check the Pinelabs device for void transactions.
[ INFO] [] [http-nio-8181-exec-4] (11 Feb 2020 12:06:36) (ThirdPartyPaymentServiceImpl.java:83) - Ajency.in :: pinelabsdto status :FAILED
[ INFO] [] [http-nio-8181-exec-4] (11 Feb 2020 12:06:36) (ThirdPartyPaymentServiceImpl.java:90) - Ajency.in :: messages: Please close open transaction (PTRID: 55713, Amount: 375.0) before initiating a new transaction from <a href='/admin/payment/OpenTransactionUi.action' target='_blank'>Open Transaction</a> / check the Pinelabs device for void transactions.
[ INFO] [] [http-nio-8181-exec-4] (11 Feb 2020 12:06:36) (ThirdPartyPaymentServiceImpl.java:96) - Ajency.in :: saved customerOrderTransaction 49 transactionId :1386485-1581402981242
[ INFO] [] [http-nio-8181-exec-4] (11 Feb 2020 12:06:36) (POSAction.java:2872) - Ajency.in :: pos action transaction status :FAILED
[ INFO] [] [http-nio-8181-exec-4] (11 Feb 2020 12:06:36) (ThirdPartyPaymentServiceImpl.java:486) - Ajency.in :: has pending transactions false for 1386485
[ INFO] [] [http-nio-8181-exec-4] (11 Feb 2020 12:06:36) (ThirdPartyPaymentServiceImpl.java:499) - Ajency.in :: hasActivePinelabsConfig true store 4213
[ INFO] [] [http-nio-8181-exec-6] (11 Feb 2020 12:06:36) (PinelabsServiceImpl.java:434) - Ajency.in :: openTransactionErrorMessage
[ INFO] [] [http-nio-8181-exec-6] (11 Feb 2020 12:06:36) (PinelabsServiceImpl.java:452) - Ajency.in :: openTransactionErrorMessage Please close open transaction (PTRID: 55713, Amount: 375.0) before initiating a new transaction from <a href='/admin/payment/OpenTransactionUi.action' target='_blank'>Open Transaction</a> / check the Pinelabs device for void transactions.
[ERROR] [] [http-nio-8181-exec-6] (11 Feb 2020 12:06:36) (PinelabsServiceImpl.java:110) - Ajency.in :: Pinelabs api call :1 : PLEASE APPROVE OPEN TXN FIRST
[ INFO] [] [http-nio-8181-exec-6] (11 Feb 2020 12:06:36) (PinelabsServiceImpl.java:124) - Ajency.in :: pinelabs response {"responseCode":1,"responseMessage":"PLEASE APPROVE OPEN TXN FIRST","plutusTransactionReferenceID":0,"additionalData":[{"tag":"ExistingReferenceId","value":"55713"},{"tag":"Amount","value":"37500"}]}
[ INFO] [] [http-nio-8181-exec-6] (11 Feb 2020 12:06:36) (PinelabsServiceImpl.java:132) - Ajency.in :: pinelabs api call for transaction 1386485-1581402993674 PlutusTransactionReferenceID:null
[ INFO] [] [http-nio-8181-exec-6] (11 Feb 2020 12:06:36) (PinelabsServiceImpl.java:134) - Ajency.in :: messages: Please close open transaction (PTRID: 55713, Amount: 375.0) before initiating a new transaction from <a href='/admin/payment/OpenTransactionUi.action' target='_blank'>Open Transaction</a> / check the Pinelabs device for void transactions.
[ INFO] [] [http-nio-8181-exec-6] (11 Feb 2020 12:06:36) (ThirdPartyPaymentServiceImpl.java:83) - Ajency.in :: pinelabsdto status :FAILED
[ INFO] [] [http-nio-8181-exec-6] (11 Feb 2020 12:06:36) (ThirdPartyPaymentServiceImpl.java:90) - Ajency.in :: messages: Please close open transaction (PTRID: 55713, Amount: 375.0) before initiating a new transaction from <a href='/admin/payment/OpenTransactionUi.action' target='_blank'>Open Transaction</a> / check the Pinelabs device for void transactions.
[ INFO] [] [http-nio-8181-exec-6] (11 Feb 2020 12:06:36) (ThirdPartyPaymentServiceImpl.java:96) - Ajency.in :: saved customerOrderTransaction 50 transactionId :1386485-1581402993674
[ INFO] [] [http-nio-8181-exec-6] (11 Feb 2020 12:06:36) (POSAction.java:2872) - Ajency.in :: pos action transaction status :FAILED
[ INFO] [] [http-nio-8181-exec-6] (11 Feb 2020 12:06:36) (ThirdPartyPaymentServiceImpl.java:486) - Ajency.in :: has pending transactions false for 1386485
[ INFO] [] [http-nio-8181-exec-6] (11 Feb 2020 12:06:36) (ThirdPartyPaymentServiceImpl.java:499) - Ajency.in :: hasActivePinelabsConfig true store 4213
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:41) (AjaxAPIResource.java:307) - Ajency.in :: payu
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:41) (PayuServiceImpl.java:148) - Ajency.in :: transaction number :1386485-1581398444741
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:41) (PayuServiceImpl.java:445) - Ajency.in :: fetching payu config for store 4033
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:41) (PayuServiceImpl.java:449) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@5418f7c
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:41) (PayuServiceImpl.java:453) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@5418f7c qrid:STQI-4033-136227
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:41) (PayuServiceImpl.java:172) - Ajency.in :: making url call to  https://mobiletest.payu.in/merchant/postservice.php
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:41) (PayuApiRequest.java:53) - data : vDy3i7|check_bqr_txn_status|1386485-1581398444741|ozyEFwfA
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:41) (PayuApiRequest.java:54) - hash : 9900882ea09128ad80ed0e8620e86dcd2708983a380cf29906d407f2992b722eca4f1fb9278cef26cbe25d5ce025ba924cdffdd24cfdbd6f6531cf484fac24fb
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:41) (PayuApiRequest.java:118) - Ajency.in :: not injecting hash value null
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:41) (PayuServiceImpl.java:479) - post data to payu gateway: key=vDy3i7&command=check_bqr_txn_status&hash=9900882ea09128ad80ed0e8620e86dcd2708983a380cf29906d407f2992b722eca4f1fb9278cef26cbe25d5ce025ba924cdffdd24cfdbd6f6531cf484fac24fb&var1=1386485-1581398444741

[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:44) (PayuServiceImpl.java:497) - Ajency.in :: retval a:2:{s:6:"status";i:0;s:3:"msg";s:49:"Some error occurred while processing the request.";}
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:44) (PayuServiceImpl.java:513) - Ajency.in :: json parsing failed, trying to un-serialize postdata:key=vDy3i7&command=check_bqr_txn_status&hash=9900882ea09128ad80ed0e8620e86dcd2708983a380cf29906d407f2992b722eca4f1fb9278cef26cbe25d5ce025ba924cdffdd24cfdbd6f6531cf484fac24fb&var1=1386485-1581398444741
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:44) (PayuServiceImpl.java:558) - Ajency.in :: result:{"status":{"value":0,"type":3},"msg":{"value":"Some error occurred while processing the request.","type":8}}
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:44) (PayuServiceImpl.java:560) - Ajency.in :: status:0
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:44) (PayuServiceImpl.java:561) - Ajency.in :: status:0
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:44) (PayuServiceImpl.java:562) - Ajency.in :: msg:Some error occurred while processing the request.
[ERROR] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:44) (PayuServiceImpl.java:607) - Ajency.in :: Payu api call error 0 Some error occurred while processing the request.
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:44) (PayuServiceImpl.java:526) - Ajency.in :: failed to un-serialize  postdata:key=vDy3i7&command=check_bqr_txn_status&hash=9900882ea09128ad80ed0e8620e86dcd2708983a380cf29906d407f2992b722eca4f1fb9278cef26cbe25d5ce025ba924cdffdd24cfdbd6f6531cf484fac24fb&var1=1386485-1581398444741
[ERROR] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:44) (PayuServiceImpl.java:536) - Ajency.in :: json parsing exception for postdata:key=vDy3i7&command=check_bqr_txn_status&hash=9900882ea09128ad80ed0e8620e86dcd2708983a380cf29906d407f2992b722eca4f1fb9278cef26cbe25d5ce025ba924cdffdd24cfdbd6f6531cf484fac24fb&var1=1386485-1581398444741
org.codehaus.jackson.JsonParseException: Unexpected character ('a' (code 97)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@21b5c361; line: 1, column: 2]
        at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
        at org.codehaus.jackson.impl.ReaderBasedParser._handleUnexpectedValue(ReaderBasedParser.java:1198)
        at org.codehaus.jackson.impl.ReaderBasedParser.nextToken(ReaderBasedParser.java:485)
        at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2770)
        at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2691)
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1286)
        at org.codehaus.jackson.JsonParser.readValueAs(JsonParser.java:1337)
        at com.hk.admin.impl.service.accounting.thirdParty.PayuServiceImpl.makePayURequest(PayuServiceImpl.java:509)
        at com.hk.admin.impl.service.accounting.thirdParty.PayuServiceImpl.getStatusPayuTransaction(PayuServiceImpl.java:173)
        at com.hk.api.resource.gym.AjaxAPIResource.payuGetStatus(AjaxAPIResource.java:310)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.HkSecurityFilter.doFilter(HkSecurityFilter.java:44)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
[ERROR] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:44) (PayuServiceImpl.java:537) - Ajency.in :: serialize parsing exception for postdata:key=vDy3i7&command=check_bqr_txn_status&hash=9900882ea09128ad80ed0e8620e86dcd2708983a380cf29906d407f2992b722eca4f1fb9278cef26cbe25d5ce025ba924cdffdd24cfdbd6f6531cf484fac24fb&var1=1386485-1581398444741
de.ailis.pherialize.exceptions.UnserializeException
        at com.hk.admin.impl.service.accounting.thirdParty.PayuServiceImpl.makePayURequest(PayuServiceImpl.java:524)
        at com.hk.admin.impl.service.accounting.thirdParty.PayuServiceImpl.getStatusPayuTransaction(PayuServiceImpl.java:173)
        at com.hk.api.resource.gym.AjaxAPIResource.payuGetStatus(AjaxAPIResource.java:310)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.HkSecurityFilter.doFilter(HkSecurityFilter.java:44)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:44) (PayuServiceImpl.java:543) - {"map":{}}
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:44) (PayuServiceImpl.java:215) - Ajency.in :: payu response {"map":{}}
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:44) (PayuServiceImpl.java:222) - Ajency.in :: payu api call for transaction 1386485-1581398444741
[ INFO] [] [http-nio-8181-exec-1] (11 Feb 2020 12:07:44) (PayuServiceImpl.java:223) - Ajency.in :: messages:

[ INFO] [] [pool-24-thread-1] (11 Feb 2020 12:07:51) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (11 Feb 2020 12:07:51) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false
`

**Comment by shivam-kurtarkar** [comment]
pinelab response 
result:{"status":{"value":0,"type":3},"msg":{"value":"Some error occurred while processing the request.","type":8}}

hence some error occurred is displayed on the screen

**Comment by shivam-kurtarkar** [comment]
payu must be down

**Comment by shivam-kurtarkar** [comment]
error occurred message should be shown
