### ISSUE TITLE
Exceptions are displayed in the logs on click of initiate transaction when the message "Failed to Initiate Transaction, please try again. Error occurred, cannot initiate transaction" is displayed

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1334]
Actual result
Exceptions are displayed in the logs on click of initiate transaction when the message "Failed to Initiate Transaction, please try again. Error occurred, cannot initiate transaction" is displayed

Steps
Go to the POS screen 
scan a baarcode
Select the payment mode as payu
click on initiate transaction

```[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (POSAction.java:2819) - Ajency.in :: payment mode : 700: PayU Static QR
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (POSAction.java:2837) - Ajency.in :: trying to fetch customer order by id :1386502
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (POSAction.java:2860) - Ajency.in :: order count:0
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (ThirdPartyPaymentServiceImpl.java:496) - Ajency.in :: has pending transactions false for 1386502
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (POSAction.java:5996) - user id:5590881user gender:FEMALE
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (POSAction.java:6005) - Ajency.in :: Invoice email :5590881suraj.rathore@brightlifecare.com
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (POSAction.java:2764) - Ajency.in :: pos cart dto , coupon code: null
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (POSHelper.java:192) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (POSAction.java:3983) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (POSAction.java:3984) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (POSAction.java:2871) - Ajency.in :: customer : 684b985965a6b00d684f52ed3dd33bc7 address 3534348 store 4034
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (POSServiceImpl.java:764) - Ajency.in :: updating customer order :1386502
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (POSServiceImpl.java:775) - Ajency.in :: applied coupon code during creating customer order: null
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (POSAction.java:2880) - Ajency.in :: final payable  rounded amount :375.0
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (ThirdPartyPaymentServiceImpl.java:60) - Ajency.in :: customer order id :1386502 transaction id 1386502-1581490249161
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuServiceImpl.java:82) - Ajency.in :: transaction number :1386502-1581490249161 amount:37500
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuServiceImpl.java:443) - Ajency.in :: fetching payu config for store 4034
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuServiceImpl.java:447) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@268d5401
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuServiceImpl.java:451) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@268d5401 qrid:STQI-4034-136227
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuServiceImpl.java:106) - Ajency.in :: making url call to  https://mobiletest.payu.in/QrPayment
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuApiRequest.java:75) - data : vDy3i7|1386502-1581490249161|37500|Integrated Static QR|||3600|STQI-4034-136227|||||||||ozyEFwfA
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuApiRequest.java:76) - hash : 5b38bc2de3eb22ffcf6be8e85a81392efddf9e6074e55de192af4315737fcc45350dcbc5dc9cc906f4d19feda1a113a6981ab6b2d1b83dc83aba51e153eef042
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuServiceImpl.java:477) - post data to payu gateway: key=vDy3i7&hash=5b38bc2de3eb22ffcf6be8e85a81392efddf9e6074e55de192af4315737fcc45350dcbc5dc9cc906f4d19feda1a113a6981ab6b2d1b83dc83aba51e153eef042&txnid=1386502-1581490249161&amount=37500&productinfo=Integrated+Static+QR&expiryTime=3600&qrId=STQI-4034-136227
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuServiceImpl.java:495) - Ajency.in :: retval <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">  <head>    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />    <title>Error</title>    <link rel="shortcut icon" type="image/ico" href="https://mobiletest.payu.in/images/favicon.png" />    <link href="https://mobiletest.payu.in/css/main.css" rel="stylesheet" type="text/css" />    <!--[if IE 6]>          <link rel="stylesheet" type="text/css" href="css/ie6.css" />    <![endif]-->    <style type="text/css"></style></head><body>    <div id="header">            <div id="header" class="clearfix">                	<div		class="logo" >		</div>        </div>            	<div id="container">		<div class="paymentDetailsDiv">			<div class="paymentDetailsHeading">An Error Occurred</div>			<div class="paymentDetails">				<div class="payby"></div>				<div class="card-bg-top"></div>			<div class="card-bg-mid">					<div id="visamaster-container"></div>					<div						style="font-size: 22px; font-weight: normal; margin-top: 15px; clear: both">						<h4 align="center">							<strong> <span style="color: #FF6600">Sorry, Some Problem									Occurred.</span>							</strong>				</h4>					</div>				</div>				<div class="card-bg-bottom"></div>				<div>					<span style="font-size: 15px;"> 																	</span>				</div>		</div>		</div>	</div></body></html>
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuServiceImpl.java:511) - Ajency.in :: json parsing failed, trying to un-serialize postdata:key=vDy3i7&hash=5b38bc2de3eb22ffcf6be8e85a81392efddf9e6074e55de192af4315737fcc45350dcbc5dc9cc906f4d19feda1a113a6981ab6b2d1b83dc83aba51e153eef042&txnid=1386502-1581490249161&amount=37500&productinfo=Integrated+Static+QR&expiryTime=3600&qrId=STQI-4034-136227
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuServiceImpl.java:524) - Ajency.in :: failed to un-serialize  postdata:key=vDy3i7&hash=5b38bc2de3eb22ffcf6be8e85a81392efddf9e6074e55de192af4315737fcc45350dcbc5dc9cc906f4d19feda1a113a6981ab6b2d1b83dc83aba51e153eef042&txnid=1386502-1581490249161&amount=37500&productinfo=Integrated+Static+QR&expiryTime=3600&qrId=STQI-4034-136227
[ERROR] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuServiceImpl.java:534) - Ajency.in :: json parsing exception for postdata:key=vDy3i7&hash=5b38bc2de3eb22ffcf6be8e85a81392efddf9e6074e55de192af4315737fcc45350dcbc5dc9cc906f4d19feda1a113a6981ab6b2d1b83dc83aba51e153eef042&txnid=1386502-1581490249161&amount=37500&productinfo=Integrated+Static+QR&expiryTime=3600&qrId=STQI-4034-136227
org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@6497cd40; line: 1, column: 2]
	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
	at org.codehaus.jackson.impl.ReaderBasedParser._handleUnexpectedValue(ReaderBasedParser.java:1198)
	at org.codehaus.jackson.impl.ReaderBasedParser.nextToken(ReaderBasedParser.java:485)
	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2770)
	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2691)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1286)
	at org.codehaus.jackson.JsonParser.readValueAs(JsonParser.java:1337)
	at com.hk.admin.impl.service.accounting.thirdParty.PayuServiceImpl.makePayURequest(PayuServiceImpl.java:507)
	at com.hk.admin.impl.service.accounting.thirdParty.PayuServiceImpl.initiatePayuTransaction(PayuServiceImpl.java:107)
	at com.hk.admin.impl.service.accounting.ThirdPartyPaymentServiceImpl.initiateTransaction(ThirdPartyPaymentServiceImpl.java:73)
	at com.hk.web.action.admin.pos.POSAction.initiatePayment(POSAction.java:2881)
	at sun.reflect.GeneratedMethodAccessor702.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuServiceImpl.java:535) - Ajency.in :: serialize parsing exception for postdata:key=vDy3i7&hash=5b38bc2de3eb22ffcf6be8e85a81392efddf9e6074e55de192af4315737fcc45350dcbc5dc9cc906f4d19feda1a113a6981ab6b2d1b83dc83aba51e153eef042&txnid=1386502-1581490249161&amount=37500&productinfo=Integrated+Static+QR&expiryTime=3600&qrId=STQI-4034-136227
de.ailis.pherialize.exceptions.UnserializeException: Unable to unserialize unknown type <
	at de.ailis.pherialize.Unserializer.unserializeObject(Unserializer.java:132)
	at de.ailis.pherialize.Pherialize.unserialize(Pherialize.java:128)
	at com.hk.admin.impl.service.accounting.thirdParty.PayuServiceImpl.unSerialize(PayuServiceImpl.java:555)
	at com.hk.admin.impl.service.accounting.thirdParty.PayuServiceImpl.makePayURequest(PayuServiceImpl.java:521)
	at com.hk.admin.impl.service.accounting.thirdParty.PayuServiceImpl.initiatePayuTransaction(PayuServiceImpl.java:107)
	at com.hk.admin.impl.service.accounting.ThirdPartyPaymentServiceImpl.initiateTransaction(ThirdPartyPaymentServiceImpl.java:73)
	at com.hk.web.action.admin.pos.POSAction.initiatePayment(POSAction.java:2881)
	at sun.reflect.GeneratedMethodAccessor702.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuServiceImpl.java:541) - 
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuServiceImpl.java:135) - Ajency.in :: payu response 
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuServiceImpl.java:142) - Ajency.in :: payu api call for transaction 1386502-1581490249161
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (PayuServiceImpl.java:143) - Ajency.in :: messages: Error occurred, cannot initiate transaction
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (ThirdPartyPaymentServiceImpl.java:74) - Ajency.in :: payudto status :null
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (ThirdPartyPaymentServiceImpl.java:102) - Ajency.in :: saved customerOrderTransaction 105 transactionId :1386502-1581490249161
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (ThirdPartyPaymentServiceImpl.java:105) - Ajency.in :: initiate status :5
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (ThirdPartyPaymentServiceImpl.java:109) - Ajency.in :: initiate status :FAILED
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (POSAction.java:2882) - Ajency.in :: initiate status :FAILED
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (POSAction.java:2891) - Ajency.in :: pos action transaction status :FAILED
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (ThirdPartyPaymentServiceImpl.java:496) - Ajency.in :: has pending transactions false for 1386502
[ INFO] [] [http-nio-8181-exec-2] (12 Feb 2020 12:20:49) (ThirdPartyPaymentServiceImpl.java:509) - Ajency.in :: hasActivePinelabsConfig true store 4034
[ INFO] [] [pool-24-thread-1] (12 Feb 2020 12:21:36) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-24-thread-1] (12 Feb 2020 12:21:36) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false

```

**Comment by shivam-kurtarkar** [comment]
payu is down
