### ISSUE TITLE
transaction status is failed when cancelled from postman.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1341]
Actual result
transaction status is failed when cancelled from postman.

Steps 
go to the pos screen 
scan a barcode
Select the payment mode as payu
initiate the transaction
cancel the transaction from postman

```
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (AjaxAPIResource.java:318) - Ajency.in :: payu 
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuServiceImpl.java:220) - Ajency.in :: transaction number :1386508-1581569257482
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuServiceImpl.java:450) - Ajency.in :: fetching payu config for store 4067
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuServiceImpl.java:454) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@6e42f1c7
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuServiceImpl.java:458) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@6e42f1c7 qrid:STQI-403301-136227
[ERROR] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuServiceImpl.java:252) - Ajency.in :: Error occurred while injecting incorrect hash 
java.lang.NullPointerException
	at com.hk.admin.impl.service.accounting.thirdParty.PayuServiceImpl.cancelPayuTransaction(PayuServiceImpl.java:245)
	at com.hk.api.resource.gym.AjaxAPIResource.payuCancel(AjaxAPIResource.java:321)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.HkSecurityFilter.doFilter(HkSecurityFilter.java:44)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuServiceImpl.java:262) - Ajency.in :: making url call to   https://mobiletest.payu.in/merchant/postservice.php
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuApiRequest.java:53) - data : vDy3i7|cancel_qr_payment|{"transactionId":"1386508-1581569257482"}|ozyEFwfA
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuApiRequest.java:54) - hash : bf9f0f2c6bbee7de213f4b371d730bd105873f68f667ecbc2700c0e60706bafc7a1184b8207dcbe23efe4f73112d1bc0785c866e189a9028c9ffbe116228d2f5
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuApiRequest.java:118) - Ajency.in :: not injecting hash value null
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuServiceImpl.java:484) - post data to payu gateway: key=vDy3i7&command=cancel_qr_payment&hash=bf9f0f2c6bbee7de213f4b371d730bd105873f68f667ecbc2700c0e60706bafc7a1184b8207dcbe23efe4f73112d1bc0785c866e189a9028c9ffbe116228d2f5&var1=%7B%22transactionId%22%3A%221386508-1581569257482%22%7D
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuServiceImpl.java:502) - Ajency.in :: retval {"status":"failed","message":"There is no [in progress] transaction with given transactionId","errorCode":"E2019"}
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuServiceImpl.java:546) - {"status":"failed","message":"There is no [in progress] transaction with given transactionId","errorCode":"E2019","map":{}}
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuServiceImpl.java:279) - Ajency.in :: payu error E2019::There is no [in progress] transaction with given transactionId
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuServiceImpl.java:283) - Ajency.in :: payu response {"status":"failed","message":"There is no [in progress] transaction with given transactionId","errorCode":"E2019","map":{}}
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuServiceImpl.java:293) - Ajency.in :: payu api call for transaction 1386508-1581569257482
[ INFO] [] [http-nio-8181-exec-1] (13 Feb 2020 10:24:08) (PayuServiceImpl.java:294) - Ajency.in :: messages: 

```
![image](https://user-images.githubusercontent.com/54023516/74402644-de290c80-4e4a-11ea-9844-08e194ed19a1.png)
![image](https://user-images.githubusercontent.com/54023516/74402656-e5e8b100-4e4a-11ea-9986-929daad4487b.png)

![image](https://user-images.githubusercontent.com/54023516/74402624-cd789680-4e4a-11ea-8c4a-750addbb58df.png)

**Comment by sharangsamonkar** [comment]
use unmapped status and mark the payment as cancelled if the unmapped status is user_cancelled

**Comment by larissa-c-d** [comment]
```
[ INFO] [] [http-nio-8181-exec-2] (14 Feb 2020 19:20:41) (PayuServiceImpl.java:438) - Ajency.in :: customerOrderTransaction details:: {"mihpayid":"9854897821","mode":"ISBQR","status":"failure","txnid":"1384453-1581688210809","amount":"5.00","key":"KJjiBk","addedon":"2020-02-14 19:20:12","productinfo":"Integrated Static QR","firstname":"","lastname":"","address1":"","address2":"","city":"","state":"","country":"","zipcode":"","email":"","phone":"","udf1":"3600","udf2":"STQI-IM4033t-161481","udf3":"","udf4":"","udf5":"","udf6":"","udf7":"","udf8":"","udf9":"","udf10":"","field0":"","field1":"","field2":"","field3":"","field4":"","field5":"","field6":"","field7":"","field8":"","field9":"Cancelled by merchant","error":"E2020","unmappedstatus":"userCancelled","hash":"591d04aec66ab2d1ccb13d45bcd67e48b9eb3d0fac3cb7760faf5bd7b6b1e71084516297bbdafe975a1f93b449ad1dfbe1c0313836139755690ac8eef6e6afb6","bankcode":"ISBQR","map":{}}
```
