### ISSUE TITLE
transaction status is not updated on dashboard

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1356]
Actual result
transaction status is not updated on dashboard, after issue #1354 

Steps
Go to the pos screen 
select the payment mode as payu
Click on initiate transaction
complete the payment
Click on get payment status
Click on cancel

```
[ INFO] [] [http-nio-8181-exec-10] (14 Feb 2020 15:17:51) (PayuServiceImpl.java:446) - Ajency.in :: creating new customerOrderTransactionDetailsPayu1386538-1581673485018
[ INFO] [] [http-nio-8181-exec-10] (14 Feb 2020 15:17:51) (PayuServiceImpl.java:478) - Ajency.in :: Saved customerOrderTransactionDetailsPayu
[ INFO] [] [http-nio-8181-exec-10] (14 Feb 2020 15:17:51) (ThirdPartyPaymentServiceImpl.java:228) - Ajency.in :: customer
[ INFO] [] [http-nio-8181-exec-10] (14 Feb 2020 15:17:51) (ThirdPartyPaymentServiceImpl.java:520) - Ajency.in :: has pending transactions true
[ INFO] [] [http-nio-8181-exec-10] (14 Feb 2020 15:17:51) (POSAction.java:3076) - Ajency.in :: hasPendingOrCompleteTransactions :true
[ INFO] [] [http-nio-8181-exec-10] (14 Feb 2020 15:17:51) (POSAction.java:3078) - Ajency.in :: customer name:larissa phone:9552519582 email:null pincode: null gender:FEMALE
[ INFO] [] [http-nio-8181-exec-10] (14 Feb 2020 15:17:51) (ThirdPartyPaymentServiceImpl.java:520) - Ajency.in :: has pending transactions true
[ INFO] [] [http-nio-8181-exec-10] (14 Feb 2020 15:17:51) (ThirdPartyPaymentServiceImpl.java:543) - Ajency.in :: hasActivePinelabsConfig true store 4067
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (POSAction.java:3101) - Ajency.in :: order count:0
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (POSAction.java:3109) - Ajency.in :: Customer Order Transaction Id286
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (ThirdPartyPaymentServiceImpl.java:278) - Ajency.in :: cancelling transaction, id:286
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (ThirdPartyPaymentServiceImpl.java:134) - Ajency.in :: user 16067491 customerOrder Transcation id 286
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (ThirdPartyPaymentServiceImpl.java:138) - Ajency.in :: payu get status ...3
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (ThirdPartyPaymentServiceImpl.java:183) - Ajency.in :: payu getting status from db..
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (ThirdPartyPaymentServiceImpl.java:228) - Ajency.in :: customer
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (ThirdPartyPaymentServiceImpl.java:306) - Ajency.in :: order count:0
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (ThirdPartyPaymentServiceImpl.java:350) - Ajency.in :: transaction already succeded, making a void call id:286
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (ThirdPartyPaymentServiceImpl.java:351) - Ajency.in :: making void api call for transaction id (mihpayid/ptrid):9853405223
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (ThirdPartyPaymentServiceImpl.java:359) - Ajency.in :: customer order transaction id :286 refundTransactionNumber Ref286-1581673766221
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (PayuServiceImpl.java:336) - Ajency.in :: transaction number :1386538-1581673485018 refundTransactionNumber:Ref286-1581673766221 transactinoAmount:6 mihpayid:9853405223
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (PayuServiceImpl.java:504) - Ajency.in :: fetching payu config for store 4067
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (PayuServiceImpl.java:508) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@4810cf10
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (PayuServiceImpl.java:512) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@4810cf10 qrid:STQI-IM4033t-161481
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (PayuServiceImpl.java:531) - Ajency.in :: USING PROD CREDENTIALS 
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (PayuServiceImpl.java:553) - Ajency.in :: error occured while puttng prod credentials
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (PayuServiceImpl.java:372) - Ajency.in :: USING PROD URL 
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (PayuServiceImpl.java:381) - Ajency.in :: making url call to   https://info.payu.in/merchant/postservice.php
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (PayuApiRequest.java:53) - data : KJjiBk|cancel_refund_transaction|9853405223|bdLqQhSG
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (PayuApiRequest.java:54) - hash : ebd5aeec6b0996194cd85ef60736788a53ac961b754b4014272f757af9fb34d540d42e01a637021c7d7603dae2b17c641ebd354de0300071fa1f9953ac9d62d8
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:26) (PayuServiceImpl.java:571) - post data to payu gateway: key=KJjiBk&command=cancel_refund_transaction&hash=ebd5aeec6b0996194cd85ef60736788a53ac961b754b4014272f757af9fb34d540d42e01a637021c7d7603dae2b17c641ebd354de0300071fa1f9953ac9d62d8&var1=9853405223&var2=Ref286-1581673766221&var3=6
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:29) (PayuServiceImpl.java:589) - Ajency.in :: retval a:6:{s:6:"status";i:1;s:3:"msg";s:21:"Refund Request Queued";s:10:"request_id";s:10:"6629592835";s:12:"bank_ref_num";N;s:8:"mihpayid";i:9853405223;s:10:"error_code";i:102;}
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:29) (PayuServiceImpl.java:604) - Ajency.in :: json parsing failed, trying to un-serialize postdata:key=KJjiBk&command=cancel_refund_transaction&hash=ebd5aeec6b0996194cd85ef60736788a53ac961b754b4014272f757af9fb34d540d42e01a637021c7d7603dae2b17c641ebd354de0300071fa1f9953ac9d62d8&var1=9853405223&var2=Ref286-1581673766221&var3=6
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:29) (PayuServiceImpl.java:648) - Ajency.in :: result:{"status":{"value":1,"type":3},"msg":{"value":"Refund Request Queued","type":8},"request_id":{"value":"6629592835","type":8},"bank_ref_num":{"type":-1},"mihpayid":{"value":9853405223,"type":4},"error_code":{"value":102,"type":3}}
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:29) (PayuServiceImpl.java:650) - Ajency.in :: status:1
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:29) (PayuServiceImpl.java:651) - Ajency.in :: status:1
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:29) (PayuServiceImpl.java:652) - Ajency.in :: msg:Refund Request Queued
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:29) (PayuServiceImpl.java:633) - {"status":"success","message":"Refund Request Queued","errorCode":"102","mihpayid":"9853405223","requestId":"6629592835","map":{}}
[ERROR] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:29) (PayuServiceImpl.java:418) - Exception while calling payu api 
org.springframework.orm.hibernate4.HibernateSystemException: Unknown entity: com.hk.rest.response.thirdPartyPayment.PayuApiResponse; nested exception is org.hibernate.MappingException: Unknown entity: com.hk.rest.response.thirdPartyPayment.PayuApiResponse
	at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:218)
	at org.springframework.orm.hibernate4.HibernateTemplate.doExecute(HibernateTemplate.java:344)
	at org.springframework.orm.hibernate4.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:309)
	at org.springframework.orm.hibernate4.HibernateTemplate.merge(HibernateTemplate.java:758)
	at com.hk.impl.dao.BaseDaoImpl.save(BaseDaoImpl.java:253)
	at com.hk.admin.impl.service.accounting.thirdParty.PayuServiceImpl.voidPayuTransaction(PayuServiceImpl.java:398)
	at com.hk.admin.impl.service.accounting.ThirdPartyPaymentServiceImpl.cancelTransaction(ThirdPartyPaymentServiceImpl.java:363)
	at com.hk.web.action.admin.pos.POSAction.cancelPayment(POSAction.java:3113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:155)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.MappingException: Unknown entity: com.hk.rest.response.thirdPartyPayment.PayuApiResponse
	at org.hibernate.internal.SessionFactoryImpl.getEntityPersister(SessionFactoryImpl.java:1096)
	at org.hibernate.internal.SessionImpl.getEntityPersister(SessionImpl.java:1479)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:163)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:85)
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:876)
	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:858)
	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:863)
	at org.springframework.orm.hibernate4.HibernateTemplate$22.doInHibernate(HibernateTemplate.java:763)
	at org.springframework.orm.hibernate4.HibernateTemplate.doExecute(HibernateTemplate.java:341)
	... 79 more
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:29) (PayuServiceImpl.java:422) - Ajency.in :: payu api call for transaction 1386538-1581673485018
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:29) (PayuServiceImpl.java:423) - Ajency.in :: messages: Error occurred, cannot get status.
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:29) (ThirdPartyPaymentServiceImpl.java:373) - Ajency.in :: saving void transaction details .. customer order transactin id:286 mihpayid id:null
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:29) (POSAction.java:3117) - Ajency.in :: pos action transaction status :VOID
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:29) (ThirdPartyPaymentServiceImpl.java:530) - Ajency.in :: has pending transactions false for 1386538
[ INFO] [] [http-nio-8181-exec-5] (14 Feb 2020 15:19:29) (ThirdPartyPaymentServiceImpl.java:543) - Ajency.in :: hasActivePinelabsConfig true store 4067



[ INFO] [] [pool-24-thread-1] (14 Feb 2020 15:20:00) (UploadUsersScheduler.java:52) - Ajency.in :: Schedule Upload Users ::  Upload Users Campaign Cron Executed:1581673800001
[ INFO] [] [pool-24-thread-1] (14 Feb 2020 15:20:00) (UploadUsersScheduler.java:68) - Ajency.in :: Schedule Upload Users :: uploadUsersEnableCron : true uploadUsersThreshold : 2000 uploadUsersEmailAddress : analytics@brightlifecare.com,retail.tech@brightlifecare.com uploadUsersCronStartTime : 22:00:00 uploadUsersPerDayLimit : 800

```
![image](https://user-images.githubusercontent.com/54023516/74521845-1b22fb00-4f40-11ea-8ded-be0a41a7117f.png)

**Comment by larissa-c-d** [comment]
![image](https://user-images.githubusercontent.com/54023516/74535218-61d21e80-4f5b-11ea-8c61-d86a286724c1.png)
displayed in request tab
