### ISSUE TITLE
Denomination,	Number of Vouchers Uploaded,Success,Failure,Action, does not contain values if the value of NO_OF_VOUCHERS_TO_BE_UPLOADED is in decimal

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1361]
Actual result
Denomination,	Number of Vouchers Uploaded,Success,Failure,Action, does not contain values if the value of NO_OF_VOUCHERS_TO_BE_UPLOADED is in decimal

Steps
Go to the paytm voucher upload UI 
Upload an excel with the NO_OF_VOUCHERS_TO_BE_UPLOADED as 1.5

```


[ INFO] [] [pool-23-thread-1] (17 Feb 2020 11:13:57) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-23-thread-1] (17 Feb 2020 11:13:57) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false
[ INFO] [] [http-nio-8080-exec-10] (17 Feb 2020 11:14:09) (VoucherGenerationAction.java:68) - Ajency.in :: VOUCHER GENERATION :: voucherUploadHistoryList 10
[ INFO] [] [pool-29-thread-1] (17 Feb 2020 11:14:10) (PaymentVoucherServiceImpl.java:405) - Ajency.in :: noOfVouchersToBeUploaded 1.5 300 2/2/2020 00:00:00 11/3/2020 00:00:00
[ERROR] [] [pool-29-thread-1] (17 Feb 2020 11:14:10) (PaymentVoucherServiceImpl.java:532) - Ajency.in :: Exception @ Row:2For input string: "1.5"
java.lang.NumberFormatException: For input string: "1.5"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at com.hk.admin.impl.service.PaymentVoucherServiceImpl.generatePaytmVouchers(PaymentVoucherServiceImpl.java:449)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy174.generatePaytmVouchers(Unknown Source)
	at com.hk.web.action.admin.VoucherGenerationAction$1.run(VoucherGenerationAction.java:97)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ INFO] [] [pool-29-thread-1] (17 Feb 2020 11:14:10) (PaymentVoucherServiceImpl.java:536) - Ajency.in :: uploadMap 0
[ INFO] [] [pool-29-thread-1] (17 Feb 2020 11:14:10) (AdminEmailManager.java:454) - Ajency.in :: Voucher Upload Email Sending to  larissa@ajency.in jagriti.dhawan 15563757
[ INFO] [] [pool-29-thread-1] (17 Feb 2020 11:14:10) (AdminEmailManager.java:464) - Ajency.in :: Voucher Email ::  Sending email to  larissa@ajency.in jagriti.dhawan
[ INFO] [] [pool-29-thread-1] (17 Feb 2020 11:14:10) (PaymentVoucherServiceImpl.java:568) - Ajency.in :: Email sent true
[ INFO] [] [pool-29-thread-1] (17 Feb 2020 11:14:10) (PaymentVoucherServiceImpl.java:539) - Ajency.in :: uploadStatusFile /usr/local/projects/rejuvenate/HealthKartWork/adminDownloads/paytm_voucher_generation/uploadVoucherDetails.xls
[ INFO] [] [http-nio-8080-exec-2] (17 Feb 2020 11:14:21) (VoucherGenerationAction.java:68) - Ajency.in :: VOUCHER GENERATION :: voucherUploadHistoryList 10
[ INFO] [] [http-nio-8080-exec-3] (17 Feb 2020 11:18:33) (VoucherGenerationAction.java:68) - Ajency.in :: VOUCHER GENERATION :: voucherUploadHistoryList 10
[ INFO] [] [pool-23-thread-1] (17 Feb 2020 11:18:57) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-23-thread-1] (17 Feb 2020 11:18:57) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false
[ INFO] [] [pool-23-thread-1] (17 Feb 2020 11:20:00) (UploadUsersScheduler.java:52) - Ajency.in :: Schedule Upload Users ::  Upload Users Campaign Cron Executed:1581918600000
[ INFO] [] [pool-23-thread-1] (17 Feb 2020 11:20:00) (UploadUsersScheduler.java:68) - Ajency.in :: Schedule Upload Users :: uploadUsersEnableCron : false uploadUsersThreshold : 2000 uploadUsersEmailAddress : analytics@brightlifecare.com,retail.tech@brightlifecare.com uploadUsersCronStartTime : 11:23:00 uploadUsersPerDayLimit : 800

```

![image](https://user-images.githubusercontent.com/54023516/74627317-7b03e680-5178-11ea-8d6f-1472586c2d8f.png)
![image](https://user-images.githubusercontent.com/54023516/74626876-2875fa80-5177-11ea-8a57-91139035ce33.png)
![image](https://user-images.githubusercontent.com/54023516/74626891-362b8000-5177-11ea-8888-5cc206c6fc42.png)
![image](https://user-images.githubusercontent.com/54023516/74627027-a20de880-5177-11ea-93c5-f36f5ad60b47.png)

**Comment by larissa-c-d** [comment]
Entry will not be made on the listing page if the row fails, according to the new approach.
