### ISSUE TITLE
cannot initiate transaction

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#1387]
```
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (POSAction.java:2819) - Ajency.in :: payment mode : 700: PayU Static QR
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (POSAction.java:2837) - Ajency.in :: trying to fetch customer order by id :1386585
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (POSAction.java:2860) - Ajency.in :: order count:0
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (ThirdPartyPaymentServiceImpl.java:531) - Ajency.in :: has pending transactions false for 1386585
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (POSAction.java:5999) - user id:5590881user gender:MALE
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (POSAction.java:6008) - Ajency.in :: Invoice email :5590881suraj.rathore@brightlifecare.com
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (POSAction.java:2764) - Ajency.in :: pos cart dto , coupon code: null
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (POSHelper.java:192) - Ajency.in:: postcart dto is not null 
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (POSAction.java:3986) - offer dto is null ?true, offer id =null
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (POSAction.java:3987) - couponCode val==============null
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (POSAction.java:2871) - Ajency.in :: customer : 684b985965a6b00d684f52ed3dd33bc7 address 3534527 store 4067
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (POSServiceImpl.java:764) - Ajency.in :: updating customer order :1386585
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (POSServiceImpl.java:775) - Ajency.in :: applied coupon code during creating customer order: null
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (POSAction.java:2880) - Ajency.in :: final payable  rounded amount :6.0
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (ThirdPartyPaymentServiceImpl.java:60) - Ajency.in :: customer order id :1386585 transaction id 1386585-1582118109562
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (PayuServiceImpl.java:80) - Ajency.in :: transaction number :1386585-1582118109562 amount:6
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (PayuServiceImpl.java:489) - Ajency.in :: fetching payu config for store 4067
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (PayuServiceImpl.java:493) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@710d8443
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (PayuServiceImpl.java:497) - Ajency.in :: store payu config :com.hk.domain.payment.thirdParty.StorePayuConfig@710d8443 qrid:STQI-406704-136227
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (PayuServiceImpl.java:516) - Ajency.in :: USING PROD CREDENTIALS 
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (PayuServiceImpl.java:538) - Ajency.in :: error occured while puttng prod credentials
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (PayuServiceImpl.java:107) - Ajency.in :: USING PROD URL 
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (PayuServiceImpl.java:117) - Ajency.in :: making url call to  https://secure.payu.in/QrPayment
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (PayuApiRequest.java:75) - data : KJjiBk|1386585-1582118109562|6|Integrated Static QR|||3600|STQI-406704-136227|||||||||bdLqQhSG
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (PayuApiRequest.java:76) - hash : 4f59024295576f3a3e537231fbbfde8957638fe18f70229a89a6621c775048bfc83e4caf17502112e6667e40ee7fcefaff2f517a8f4e2bce385743e1fab2c1c8
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:09) (PayuServiceImpl.java:556) - post data to payu gateway: key=KJjiBk&hash=4f59024295576f3a3e537231fbbfde8957638fe18f70229a89a6621c775048bfc83e4caf17502112e6667e40ee7fcefaff2f517a8f4e2bce385743e1fab2c1c8&txnid=1386585-1582118109562&amount=6&productinfo=Integrated+Static+QR&expiryTime=3600&qrId=STQI-406704-136227
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:12) (PayuServiceImpl.java:574) - Ajency.in :: retval {"status":"failed","message":"qrId does not belong to integrated static qr.","errorCode":"E2024"}
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:12) (PayuServiceImpl.java:618) - {"status":"failed","message":"qrId does not belong to integrated static qr.","errorCode":"E2024","map":{}}
[ERROR] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:12) (PayuServiceImpl.java:122) - Ajency.in :: payu api call :failed : qrId does not belong to integrated static qr.
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:12) (PayuServiceImpl.java:136) - Ajency.in :: payu error E2024::qrId does not belong to integrated static qr.
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:12) (PayuServiceImpl.java:145) - Ajency.in :: payu response {"status":"failed","message":"qrId does not belong to integrated static qr.","errorCode":"E2024","map":{}}
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:12) (PayuServiceImpl.java:152) - Ajency.in :: payu api call for transaction 1386585-1582118109562
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:12) (PayuServiceImpl.java:153) - Ajency.in :: messages: 
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:12) (ThirdPartyPaymentServiceImpl.java:75) - Ajency.in :: payudto status :FAILED
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:12) (ThirdPartyPaymentServiceImpl.java:103) - Ajency.in :: saved customerOrderTransaction 466 transactionId :1386585-1582118109562
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:12) (ThirdPartyPaymentServiceImpl.java:106) - Ajency.in :: initiate status :5
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:12) (ThirdPartyPaymentServiceImpl.java:110) - Ajency.in :: initiate status :FAILED
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:12) (POSAction.java:2882) - Ajency.in :: initiate status :FAILED
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:12) (POSAction.java:2891) - Ajency.in :: pos action transaction status :FAILED
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:12) (ThirdPartyPaymentServiceImpl.java:531) - Ajency.in :: has pending transactions false for 1386585
[ INFO] [] [http-nio-8181-exec-9] (19 Feb 2020 18:45:12) (ThirdPartyPaymentServiceImpl.java:544) - Ajency.in :: hasActivePinelabsConfig true store 4067
[ERROR] [] [Thread-7] (19 Feb 2020 18:45:14) (Worker.java:439) - Unable to initialize after 20 attempts. Shutting down.
java.lang.RuntimeException: com.amazonaws.services.kinesis.leases.exceptions.DependencyException: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 192.168.70.62:4568 [/192.168.70.62] failed: Connection refused (Connection refused)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:534)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:436)
	at com.hk.web.listener.KinesisConsumer$1.run(KinesisConsumer.java:90)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.services.kinesis.leases.exceptions.DependencyException: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 192.168.70.62:4568 [/192.168.70.62] failed: Connection refused (Connection refused)
	at com.amazonaws.services.kinesis.leases.impl.LeaseManager.createLeaseTableIfNotExists(LeaseManager.java:135)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibLeaseCoordinator.initialize(KinesisClientLibLeaseCoordinator.java:307)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:495)
	... 3 more
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 192.168.70.62:4568 [/192.168.70.62] failed: Connection refused (Connection refused)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1114)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1064)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2954)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2930)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeCreateTable(AmazonDynamoDBClient.java:899)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.createTable(AmazonDynamoDBClient.java:874)
	at com.amazonaws.services.kinesis.leases.impl.LeaseManager.createLeaseTableIfNotExists(LeaseManager.java:128)
	... 5 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 192.168.70.62:4568 [/192.168.70.62] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy255.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1236)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	... 16 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory$TrustingSocketFactory.connectSocket(ApacheConnectionManagerFactory.java:184)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 31 more
[ INFO] [] [Thread-7] (19 Feb 2020 18:45:14) (Worker.java:768) - Worker shutdown requested.
[ INFO] [] [Thread-7] (19 Feb 2020 18:45:14) (Worker.java:811) - All record processors have been shutdown successfully.
[ INFO] [] [Thread-7] (19 Feb 2020 18:45:14) (Worker.java:785) - Starting worker's final shutdown.
[ INFO] [] [Thread-7] (19 Feb 2020 18:45:14) (Worker.java:448) - Worker loop is complete. Exiting from worker.

```

**Comment by larissa-c-d** [comment]
issue resolved
