### ISSUE TITLE
Exception while checking in the barcode on Aqua from Bright

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1470]
[ INFO] [] [http-nio-8080-exec-7] (08 Apr 2020 12:40:05) (AdminInventoryServiceImpl.java:292) - Ajency.in :: INV-CHECKIN-CHECKOUT :: updating sku item status to: 10 for sku item id: 8763073 barcode: IVM-493-96475
[ERROR] [] [pool-13-thread-1] (08 Apr 2020 12:40:06) (CommunicationServiceImpl.java:56) - Exception while sending to producer
java.lang.NullPointerException
        at com.hk.kinesis.producer.KinesisProducer.send(KinesisProducer.java:141)
        at com.hk.impl.communication.CommunicationServiceImpl.sendCallForAquaInvSync(CommunicationServiceImpl.java:52)
        at com.hk.web.action.admin.inventory.InventoryCheckinAction.lambda$saveStockTransfer$0(InventoryCheckinAction.java:687)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[ INFO] [] [http-nio-8080-exec-9] (08 Apr 2020 12:40:13) (StockTransferServiceImpl.java:1284) - Validate the checkout and checkin quantities of stock transfer - 106505 before closing it.
[ INFO] [] [http-nio-8080-exec-9] (08 Apr 2020 12:40

**Comment by shivam-kurtarkar** [comment]
kinesis error
