### ISSUE TITLE
Exception while returning HK.com order

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1555]
Gateway order id- HKA-08231-23584085
Holisol store

![image](https://user-images.githubusercontent.com/14803102/80710946-31872e80-8b0d-11ea-95e1-06378a12dbca.png)

ection refused)
[ INFO] [] [pool-2-thread-2] (30 Apr 2020 18:01:58) (HkHttpClient.java:294) - Ajency.in :: IO Exception Stacktrace: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:286)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:252)
        at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:238)
        at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:205)
        at com.hk.impl.service.opr.OprStatusSyncToApiServiceImpl$1.run(OprStatusSyncToApiServiceImpl.java:783)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

[ERROR] [] [pool-2-thread-2] (30 Apr 2020 18:01:58) (OprStatusSyncToApiServiceImpl.java:785) - Exception while updating opr li status on API for : HKA-08231-23584085 action: markReturnInitiated
[ INFO] [] [http-nio-8080-exec-9] (30 Apr 2020 18:02:38) (RPWarehouseCheckinAction.java:206) - rp line item id:323784
[ INFO] [] [http-nio-8080-exec-9] (30 Apr 2020 18:02:38) (RPWarehouseCheckinAction.java:207) - rp line item, line item id:6879375
[ INFO] [] [http-nio-8080-exec-9] (30 Apr 2020 18:02:38) (RPWarehouseCheckinAction.java:208) - rpline item is freebie?:10
[ INFO] [] [http-nio-8080-exec-9] (30 Apr 2020 18:02:38) (ReversePickupServiceImpl.java:300) - Checking in RP line item - 323784, for SO ID - 5174499-S31634, barcode - IVM-455-275553, for reason - 910
[ INFO] [] [http-nio-8080-exec-9] (30 Apr 2020 18:02:38) (AdminInventoryServiceImpl.java:292) - Ajency.in :: INV-CHECKIN-CHECKOUT :: updating sku item status to: 40 for sku item id: 8516335 barcode: IVM-455-275553
[ INFO] [] [http-nio-8080-exec-9] (30 Apr 2020 18:02:38) (ReversePickupServiceImpl.java:311) - Extra IHC Call.. Calling IHC from checkInRpLineItem, case Damaged for PV NUT5282-14
[ INFO] [] [http-nio-8080-exec-9] (30 Apr 2020 18:02:38) (OprStatusSyncToApiServiceImpl.java:775) - Ajency.in:: In method updateOPRLiStatusOnHKEdge.
[ INFO] [] [pool-2-thread-3] (30 Apr 2020 18:02:38) (HkHttpClient.java:290) - Ajency.in :: IO Exception: Connection refused (Connection refused)
[ INFO] [] [pool-2-thread-3] (30 Apr 2020 18:02:38) (HkHttpClient.java:294) - Ajency.in :: IO Exception Stacktrace: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:286)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:252)
        at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:238)
        at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:205)
        at com.hk.impl.service.opr.OprStatusSyncToApiServiceImpl$1.run(OprStatusSyncToApiServiceImpl.java:783)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

[ERROR] [] [pool-2-thread-3] (30 Apr 2020 18:02:38) (OprStatusSyncToApiServiceImpl.java:785) - Exception while updating opr li status on API for : HKA-08231-23584085 action: markReturned
[ INFO] [] [http-nio-8080-exec-9] (30 Apr 2020 18:02:38) (HkHttpClient.java:148) - Ajency.in :: io exception
[ INFO] [] [http-nio-8080-exec-9] (30 Apr 2020 18:02:38) (HkHttpClient.java:149) - Connection refused (Connection refused)

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/80711611-444e3300-8b0e-11ea-9ca9-d3f7cd8a7d7b.png)
