### ISSUE TITLE
Exception in logs and item leveloffer could not be applied message when applying Buy 1 Get 1 on MRP offer

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1639]
mum mahavir nagar
Scan 2 barcode of NUT1367-39
2 barode of NUT1367-41
Apply Buy 1 Get 1 on MRP offer and observe

Actual: Exception in logs and  item level offer could not be applied message when applying Buy 1 Get 1 on MRP offer

![image](https://user-images.githubusercontent.com/14803102/82693912-fbf2e280-9c7f-11ea-8639-d1f641f1b17c.png)

![image](https://user-images.githubusercontent.com/14803102/82693963-162cc080-9c80-11ea-8c74-c7e1e2e82f55.png)

[ INFO] [] [http-nio-8181-exec-10] (22 May 2020 22:57:32) (HkVariantServiceImpl.java:149) - Ajency.in :: POS OFFER INVENTORY CHECK ::  No Variant On Action 1110 order lvl dic  flat
[ INFO] [] [http-nio-8181-exec-10] (22 May 2020 22:57:32) (HkVariantServiceImpl.java:100) - Ajency.in :: POS OFFER INVENTORY CHECK :: Offer Valid after inventory check
[ INFO] [] [http-nio-8181-exec-10] (22 May 2020 22:57:32) (HkVariantServiceImpl.java:194) - Ajency.in :: APPLY-OFFER :: making an api call to http://192.168.70.61:7070/api/offer/cart/applyOffer/179704?z.ts==1590168452815&st=1 request: {"variantList":[{"storeVariantId":74399,"quantity":2,"variantSingleMrp":5199.0,"variantSingleOfferPrice":3639,"variantSingleHkPrice":3639},{"storeVariantId":72367,"quantity":2,"variantSingleMrp":5349.0,"variantSingleOfferPrice":2599,"variantSingleHkPrice":2599}],"retailStoreId":4034,"storeId":1,"fetchPersonalizedCouponsForUserOnRetailStore":true,"fetchBxGyOffers":true}
[ INFO] [] [http-nio-8181-exec-10] (22 May 2020 22:57:32) (HkHttpClient.java:290) - Ajency.in :: IO Exception: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.apache.commons.httpclient.AutoCloseInputStream@5ef8f8fe; line: 1, column: 2]
[ INFO] [] [http-nio-8181-exec-10] (22 May 2020 22:57:32) (HkHttpClient.java:294) - Ajency.in :: IO Exception Stacktrace: org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.apache.commons.httpclient.AutoCloseInputStream@5ef8f8fe; line: 1, column: 2]
        at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
        at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2090)
        at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:606)
        at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:492)
        at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2770)
        at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2691)
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1286)
        at org.codehaus.jackson.JsonParser.readValueAs(JsonParser.java:1337)
        at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:268)
        at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:238)
        at com.hk.util.http.HkHttpClient.executePostForObject(HkHttpClient.java:205)
        at com.hk.api.edge.integration.impl.service.variant.HkVariantServiceImpl.applyOffer(HkVariantServiceImpl.java:199)
        at com.hk.web.action.admin.pos.POSAction.applyOfferOnCart(POSAction.java:5142)
        at com.hk.web.action.admin.pos.POSAction.applyOffer(POSAction.java:4785)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
        at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:56)
        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
        at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
        at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:224)
        at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:131)
        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
        at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
        at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
        at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
        at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:159)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

[ INFO] [] [http-nio-8181-exec-10] (22 May 2020 22:57:32) (HkVariantServiceImpl.java:205) - Ajency.in :: APPLY-OFFER :: applyOfferResponseWrapper null for offer: 179704
[ INFO] [] [http-nio-8181-exec-10] (22 May 2020 22:57:32) (POSAction.java:5269) - Error While applying offer :179704
[ INFO] [] [http-nio-8181-exec-10] (22 May 2020 22:57:32) (POSAction.java:5271) - Ajency.in :: APPLY-OFFER :: apply offer response null for offer id: 179704
[ INFO] [] [http-nio-8181-exec-10] (22 May 2020 22:57:32) (POSAction.java:5288) - Ajency.in :: isbxgy:true posCartDTO.getBxGyOfferDetails()==null:true
[ INFO] [] [http-nio-8181-exec-10] (22 May 2020 22:57:32) (POSAction.java:5291) - Ajency.in :: clearing offer for offer id:179704
[ INFO] [] [http-nio-8181-exec-10] (22 May 2020 22:57:32) (ThirdPartyPaymentServiceImpl.java:530) - Ajency.in :: customer order id is null.

**Comment by rohan-morje** [comment]
![image](https://user-images.githubusercontent.com/14803102/82694259-9521f900-9c80-11ea-8480-e2ca97df9cc8.png)
