### ISSUE TITLE
Null pointer exception while initiateParallelProcessing() when downloading excel file

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#806]
Create the Inventory Planner 3727
Go to Inventory Planner Excel Download -> Enter the IP ID 3727
Click on Download Plan button and observe

Null pointer exception while initiateParallelProcessing()  inthe logs

[ INFO] [] [pool-10-thread-2] (04 Dec 2019 12:13:05) (AdminInventoryServiceImpl.java:6031) - Ajency.in :: IP Download :: ip: 3727 Exception while initiateParallelProcessing()
java.lang.NullPointerException
        at com.hk.admin.impl.service.inventory.AdminInventoryServiceImpl$5.run(AdminInventoryServiceImpl.java:5992)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Shraddhar23** [comment]
Null Pointer Resolved.

**Comment by rohan-morje** [comment]
issue resolved
