### ISSUE TITLE
're generating pdf for [shipping order id] logger displayed on click of GST invoice PDF for orders placed before the implementation of Sms/Email  feature.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#809]
Actual Result
're generating pdf for [shipping order id] logger displayed on click of GST invoice PDF for orders placed before the implementation of Sms/Email  feature.

Expected Results
On click of GST invoice PDF ,The PDF should be created and stored.
Steps
Click on the GST invoice for an order placed before the implementation of the Sms /Email invoice feature.
check the logs

**Logs**

[ INFO] [] [http-nio-8080-exec-1] (04 Dec 2019 12:51:33) (SearchShippingOrderAction.java:96) - Ajency.in :: rpLineItemList size 0
**[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceAction.java:145) - Ajency.in :: re generating pdf for shipping order id 4668111**
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceDTO.java:110) - Ajency.in:: total line items for invoice > 3
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceDTO.java:114) - Ajency.in:: Invoice eligible for clubbing
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceDTO.java:159) - Ajency.in:: Product line item for invoice: TrueBasics Multivit Sport One Daily Multivitamin,  90 tablet(s)  Unflavoured 
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceDTO.java:264) - Ajency.in:: LI packmap is not empty
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceDTO.java:307) - Ajency.in:: Total invoice items > 1
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceDTO.java:159) - Ajency.in:: Product line item for invoice: MuscleBlaze Spider Shaker,  Black  700 ml 
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceDTO.java:264) - Ajency.in:: LI packmap is not empty
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceDTO.java:159) - Ajency.in:: Product line item for invoice: TrueBasics Vegan Omega 870mg of Vegetarian Omega Fatty Acids,  90 softgels 
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceDTO.java:264) - Ajency.in:: LI packmap is not empty
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceDTO.java:267) - Ajency.in:: LI packmap contains child
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceDTO.java:269) - Ajency.in:: lineitemlist size > 1
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceDTO.java:307) - Ajency.in:: Total invoice items > 2
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceServiceImpl.java:398) - Ajency.in :: pdf file path : /usr/local/tomcat/webapps/ROOT//gstInvoicePDF/SO_4668111_2019-12-04.pdf
[ERROR] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (DigitalSignatureException.java:17) - Error while generating Digital Signature for path: /usr/local/tomcat/webapps/ROOT//gstInvoicePDF/SO_4668111_2019-12-04.pdf
java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.hk.admin.util.DigitalSignatureUtil.attachDigitalSignature(DigitalSignatureUtil.java:62)
	at com.hk.admin.util.SOGSTInvoiceGenerator.generateInvoicePDF(SOGSTInvoiceGenerator.java:114)
	at com.hk.admin.impl.service.accounting.GSTInvoiceServiceImpl.generateSOGSTPdf(GSTInvoiceServiceImpl.java:402)
	at com.hk.admin.impl.service.accounting.GSTInvoiceServiceImpl.generateAndUploadInvoice(GSTInvoiceServiceImpl.java:429)
	at com.hk.web.action.core.accounting.GSTInvoiceAction.downloadInvoiceAsPdf(GSTInvoiceAction.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:52)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:188)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:120)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778)
	... 82 more
[ERROR] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (SOGSTInvoiceGenerator.java:116) - java.io.IOException: Keystore was tampered with, or password was incorrect
com.hk.exception.DigitalSignatureException: java.io.IOException: Keystore was tampered with, or password was incorrect
	at com.hk.admin.util.DigitalSignatureUtil.attachDigitalSignature(DigitalSignatureUtil.java:88)
	at com.hk.admin.util.SOGSTInvoiceGenerator.generateInvoicePDF(SOGSTInvoiceGenerator.java:114)
	at com.hk.admin.impl.service.accounting.GSTInvoiceServiceImpl.generateSOGSTPdf(GSTInvoiceServiceImpl.java:402)
	at com.hk.admin.impl.service.accounting.GSTInvoiceServiceImpl.generateAndUploadInvoice(GSTInvoiceServiceImpl.java:429)
	at com.hk.web.action.core.accounting.GSTInvoiceAction.downloadInvoiceAsPdf(GSTInvoiceAction.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:52)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:188)
	at org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:120)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WhitespaceFilter.doFilter(WhitespaceFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.WebContextFilter.doFilter(WebContextFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hk.web.filter.RememberMeFilter.doFilter(RememberMeFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.akube.framework.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.hk.admin.util.DigitalSignatureUtil.attachDigitalSignature(DigitalSignatureUtil.java:62)
	... 77 more
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778)
	... 82 more
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceServiceImpl.java:404) - Ajency.in :: new pdf created : /usr/local/tomcat/webapps/ROOT//gstInvoicePDF/SO_4668111_2019-12-04.pdf
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:39) (GSTInvoiceServiceImpl.java:432) - Ajency.in :: file key: gstInvoicePDF/2019-12-04/SO_4668111_2019-12-04.pdf
[ INFO] [] [http-nio-8080-exec-4] (04 Dec 2019 12:51:42) (GSTInvoiceAction.java:148) - Ajency.in :: pdf link : /gstInvoicePDF/SO_4668111_2019-12-04.pdf
[ INFO] [] [pool-23-thread-1] (04 Dec 2019 12:54:18) (SecurityServiceImpl.java:32) - Inside reloadSecurityCacheOnCluster
[ INFO] [] [pool-23-thread-1] (04 Dec 2019 12:54:18) (SecurityServiceImpl.java:36) - HKSecurity disabled useHkSecurity : false

**Comment by shivam-kurtarkar** [comment]
anything that does not have pdf already generated during pos and uploaded to s3
is re generated
