### ISSUE TITLE
email sent message is displayed on the pos screen,when the sending sms is failed.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#900]
Actual result
email sent message is displayed on the pos screen,when the sending sms is failed.

Expected Result
Email not sent message should be displayed.

`	... 82 more
[ INFO] [] [http-nio-8181-exec-8] (17 Dec 2019 16:03:24) (GSTInvoiceServiceImpl.java:405) - Ajency.in :: new pdf created : /usr/local/projects/tomcat_aqua_new/webapps/ROOT/gstInvoicePDF/SO_5925047_1576578804001.pdf
[ INFO] [] [http-nio-8181-exec-8] (17 Dec 2019 16:03:24) (GSTInvoiceServiceImpl.java:432) - Ajency.in :: uploading to s3 with file key: gstInvoicePDF/2019/Dec/SO_5925047_1576578804001.pdf
[ INFO] [] [http-nio-8181-exec-8] (17 Dec 2019 16:03:26) (GSTInvoiceServiceImpl.java:437) - Ajency.in :: successfully uploaded to upload pdf to aws gstInvoicePDF/2019/Dec/SO_5925047_1576578804001.pdf
[ INFO] [] [http-nio-8181-exec-8] (17 Dec 2019 16:03:26) (GSTInvoiceServiceImpl.java:445) - Ajency.in :: saved to sogstInvoiceHistory table , id:181
[ INFO] [] [http-nio-8181-exec-8] (17 Dec 2019 16:03:26) (POSAction.java:3245) - Ajency.in :: sending link for so 5925047 to customer true from store 4033
[ INFO] [] [http-nio-8181-exec-8] (17 Dec 2019 16:03:26) (GSTInvoiceServiceImpl.java:604) - Ajency.in :: user login : MOB_8B4abY1575872303978
[ INFO] [] [http-nio-8181-exec-8] (17 Dec 2019 16:03:26) (GSTInvoiceServiceImpl.java:613) - Ajency.in :: customer invoice url : http://aqua61.healthkartqa.com/core/accounting/GSTInvoiceDownload.action?customerInvoiceAsPdf=&gatewayOrderId=5925047-S35480&user=CwqwNarWyUa8SXHKJRhHAA%253D%253D
[ INFO] [] [http-nio-8181-exec-8] (17 Dec 2019 16:03:26) (GSTInvoiceServiceImpl.java:540) - Ajency.in :: sending email to email address : larissa@ajency.in
[ERROR] [] [Thread-13] (17 Dec 2019 16:03:26) (EmailServiceImpl.java:338) - EmailException in SendEmailAsyncThread.run
org.apache.commons.mail.EmailException: Sending the email to the following server failed : localhost:25
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469)
	at org.apache.commons.mail.Email.send(Email.java:1496)
	at com.hk.impl.service.EmailServiceImpl$SendEmailAsyncThread.run(EmailServiceImpl.java:336)
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;
`

![image](https://user-images.githubusercontent.com/54023516/70988002-01ec0280-20e7-11ea-8d53-b0eff1c3a008.png)

**Comment by larissa-c-d** [comment]
Issue resolved.
